

'=================================================================
'EnumDepositTypes.vb is automatically generated by the EnumDepositTypes.tt T4 file.
'Do not make any changes in the vb file.
'
'Enumeration members are gotten from a call to Proc_EnumDepositTypes in the database.
'=================================================================

Namespace SCM6Enums.StructuredEnums

Public Class DepositType
    Public ReadOnly Property Id As Integer
    Public ReadOnly Property Name As String
    Public ReadOnly Property Description As String
	Public ReadOnly Property ResourceType As eResourceType
	Public ReadOnly Property DepositTypeParameters As Dictionary(Of string, DepositTypeParameter)

    Private Sub New(ByVal id As Integer, ByVal name As String, ByVal description As String, ByVal resourceType As eResourceType, ByVal depositTypeParameters As Dictionary(Of string, DepositTypeParameter))
        Me.Id = id
        Me.Name = name
        Me.Description = description
		Me.DepositTypeParameters = depositTypeParameters
		Me.ResourceType = resourceType
    End Sub

	
   'The below DepositTypes are generated by the EnumDepositTypes.tt script (which uses Proc_EnumDepositTypes)
	Public Shared ReadOnly PMCNIH As new DepositType(1, "PMCNIH", "", CType(3, eResourceType), new Dictionary(Of String,DepositTypeParameter) From {{"StartDate", New DepositTypeParameter(2, "StartDate", "", 1,6)}})
	Public Shared ReadOnly PMCFull As new DepositType(2, "PMCFull", "", CType(3, eResourceType), new Dictionary(Of String,DepositTypeParameter) From {{"StartDate", New DepositTypeParameter(3, "StartDate", "", 2,6)}})
	Public Shared ReadOnly PMCSelective As new DepositType(3, "PMCSelective", "", CType(3, eResourceType), new Dictionary(Of String,DepositTypeParameter) From {{"StartDate", New DepositTypeParameter(4, "StartDate", "", 3,6)}})
	Public Shared ReadOnly PubMed As new DepositType(4, "PubMed", "", CType(3, eResourceType), new Dictionary(Of String,DepositTypeParameter) From {{"Abbreviation", New DepositTypeParameter(1, "Abbreviation", "", 4,2)}})
	Public Shared ReadOnly Ovid As new DepositType(5, "Ovid", "Ovid deposits for issues.", CType(6, eResourceType), Nothing)
	Public Shared ReadOnly Muse As new DepositType(6, "Muse", "", CType(3, eResourceType), Nothing)
	Public Shared ReadOnly Portico As new DepositType(7, "Portico", "Portico deposits for issues.", CType(6, eResourceType), Nothing)
	Public Shared ReadOnly DeepDyve As new DepositType(8, "DeepDyve", "", CType(3, eResourceType), Nothing)
	Public Shared ReadOnly CrossRef As new DepositType(9, "CrossRef", "", CType(3, eResourceType), Nothing)
	Public Shared ReadOnly WebOfScience As new DepositType(10, "WebOfScience", "", CType(3, eResourceType), Nothing)
	Public Shared ReadOnly PorticoArticle As new DepositType(11, "PorticoArticle", "Portico deposits for PAP/JAM articles.", CType(3, eResourceType), Nothing)
	Public Shared ReadOnly DataSalon As new DepositType(12, "DataSalon", "", CType(3, eResourceType), Nothing)
	Public Shared ReadOnly PTEPSCOAP3 As new DepositType(13, "PTEPSCOAP3", "", CType(6, eResourceType), Nothing)
	Public Shared ReadOnly ADS As new DepositType(14, "ADS", "ADS deposits for issues.", CType(6, eResourceType), Nothing)
	Public Shared ReadOnly CDS As new DepositType(15, "CDS", "CDS deposits for issues.", CType(6, eResourceType), Nothing)
	Public Shared ReadOnly KBART As new DepositType(16, "KBART", "", CType(3, eResourceType), Nothing)
	Public Shared ReadOnly OvidArticle As new DepositType(17, "OvidArticle", "Ovid deposits for PAP/JAM articles.", CType(3, eResourceType), Nothing)
	Public Shared ReadOnly RSuite As new DepositType(18, "RSuite", "RSuite deposits for issues.", CType(6, eResourceType), Nothing)
	Public Shared ReadOnly RSuiteArticle As new DepositType(19, "RSuiteArticle", "RSuite deposits for PAP/JAM articles.", CType(3, eResourceType), Nothing)
	Public Shared ReadOnly AGI As new DepositType(20, "AGI", "GeoRef deposits for articles.", CType(3, eResourceType), Nothing)
	Public Shared ReadOnly ADSArticle As new DepositType(21, "ADSArticle", "ADS deposits for PAP/JAM articles.", CType(3, eResourceType), Nothing)
	Public Shared ReadOnly CDSArticle As new DepositType(22, "CDSArticle", "CDS deposits for PAP/JAM articles.", CType(3, eResourceType), Nothing)

    ''' <summary>
    ''' Returns all valid DepositTypes
    ''' </summary>
	Public Shared Iterator Function All() As IEnumerable(Of DepositType)
			yield PMCNIH
		yield PMCFull
		yield PMCSelective
		yield PubMed
		yield Ovid
		yield Muse
		yield Portico
		yield DeepDyve
		yield CrossRef
		yield WebOfScience
		yield PorticoArticle
		yield DataSalon
		yield PTEPSCOAP3
		yield ADS
		yield CDS
		yield KBART
		yield OvidArticle
		yield RSuite
		yield RSuiteArticle
		yield AGI
		yield ADSArticle
		yield CDSArticle
	End Function
        
	Public Shared Function FromName (ByVal name as string) As DepositType
		if(string.IsNullOrEmpty(name)) then
			throw new ArgumentNullException("name")
		end if

		Dim result = All().FirstOrDefault(Function(x) x.Name = name)

		if(result isNot Nothing)
			return result
		end if

		throw new ArgumentOutOfRangeException("name", name, "Invalid DepositType")
	End Function

	''' <summary>
	''' Allows for the casting of an int type to a DepositType
	''' </summary>
	Public Shared Narrowing Operator CType(id As Integer) As DepositType
		Dim result = All().FirstOrDefault(Function(x) CInt(x) = id)
		If result IsNot Nothing Then
			Return result
		End If

		Throw New InvalidCastException("The value " + id.ToString() + " is not a valid DepositType")
	End Operator

	''' <summary>
	''' Allows for the casting of a DepositType to an integer type
	''' </summary>
	Public Shared Narrowing Operator CType(value As DepositType) As Integer
		Return value.Id
	End Operator

End Class

End Namespace

