 
'=================================================================
'DBObjectTypes.vb is automatically generated by the DBObjectsType.tt
'T4 file. Do not make any changes in the vb file.
'
'Enumeration members are gotten from a call to Proc_TypeEnumeratorsGet in the database.
'=================================================================

Namespace SCM6Enums

#Region "Lookup Type Enums"
	


 	''' <summary>
    '''Represents the types associated with Ads 
    ''' </summary>
    ''' <remarks>Represents the types associated with Ads</remarks>
Public Enum eAdType As Integer
	<Xml.Serialization.XmlEnum("1")>[SkyScrapper] = 1	
End Enum


	''' <summary>
    '''Represents the types associated with Categories 
    ''' </summary>
    ''' <remarks>Represents the types associated with Categories</remarks>

Public Enum eArticleType As Integer
	
	 <Xml.Serialization.XmlEnum("1")>[Article] = 1	
	
	 <Xml.Serialization.XmlEnum("2")>[Quiz] = 2	
	
	 <Xml.Serialization.XmlEnum("3")>[Letter] = 3	
	
	 <Xml.Serialization.XmlEnum("4")>[Correction] = 4	
	
	 <Xml.Serialization.XmlEnum("5")>[Filler] = 5	
	
	 <Xml.Serialization.XmlEnum("6")>[Wrapper] = 6	
	
	 <Xml.Serialization.XmlEnum("7")>[Newsletter] = 7	
	
	 <Xml.Serialization.XmlEnum("8")>[Proceeding] = 8	
End Enum


	''' <summary>
    '''Represents the types associated with Categories 
    ''' </summary>
    ''' <remarks>Represents the types associated with Categories</remarks>

Public Enum eCategoryType As Integer

	<Xml.Serialization.XmlEnum("1")>[TopicStatic] = 1	

	<Xml.Serialization.XmlEnum("2")>[TopicDynamic] = 2	

	<Xml.Serialization.XmlEnum("3")>[FacetCategory] = 3	

	<Xml.Serialization.XmlEnum("4")>[PublishFormat] = 4	

	<Xml.Serialization.XmlEnum("5")>[Superclassification] = 5	

	<Xml.Serialization.XmlEnum("6")>[NumberofIssues] = 6	

	<Xml.Serialization.XmlEnum("8")>[SpecialCollections] = 8	

	<Xml.Serialization.XmlEnum("9")>[ArticleClassification] = 9	

	<Xml.Serialization.XmlEnum("10")>[VirtualJournal] = 10	

	<Xml.Serialization.XmlEnum("11")>[OrganSystem] = 11	

	<Xml.Serialization.XmlEnum("12")>[AnatomyPhysiologyRevealed] = 12	

	<Xml.Serialization.XmlEnum("13")>[BookCategories] = 13	

	<Xml.Serialization.XmlEnum("14")>[MultimediaCategories] = 14	

	<Xml.Serialization.XmlEnum("15")>[BookSectionCategories] = 15	

	<Xml.Serialization.XmlEnum("16")>[Department] = 16	

	<Xml.Serialization.XmlEnum("17")>[BookUpdateCategories] = 17	

	<Xml.Serialization.XmlEnum("18")>[MGHACPTEBPPCategories] = 18	

	<Xml.Serialization.XmlEnum("19")>[ProcedureVideos] = 19	

	<Xml.Serialization.XmlEnum("20")>[AtYourFingerTips] = 20	

	<Xml.Serialization.XmlEnum("21")>[Specialties] = 21	

	<Xml.Serialization.XmlEnum("22")>[Cases] = 22	

	<Xml.Serialization.XmlEnum("23")>[LexiPharmacologicClass] = 23	

	<Xml.Serialization.XmlEnum("24")>[CMEStateAssociation] = 24	

	<Xml.Serialization.XmlEnum("25")>[PrintPublication] = 25	

	<Xml.Serialization.XmlEnum("26")>[GbosSectionCategories] = 26	

	<Xml.Serialization.XmlEnum("27")>[Topics] = 27	

	<Xml.Serialization.XmlEnum("28")>[OutcomeMeasures] = 28	

	<Xml.Serialization.XmlEnum("29")>[Specialty] = 29	

	<Xml.Serialization.XmlEnum("30")>[GenCategory] = 30	

	<Xml.Serialization.XmlEnum("31")>[Browse] = 31	

	<Xml.Serialization.XmlEnum("32")>[PrintPub] = 32	

	<Xml.Serialization.XmlEnum("33")>[SectionContentType] = 33	

	<Xml.Serialization.XmlEnum("34")>[Algorithms] = 34	

	<Xml.Serialization.XmlEnum("35")>[BookFlag] = 35	

	<Xml.Serialization.XmlEnum("36")>[Ancillary] = 36	

	<Xml.Serialization.XmlEnum("38")>[AAPSyndication] = 38	

	<Xml.Serialization.XmlEnum("39")>[Subjects] = 39	

	<Xml.Serialization.XmlEnum("40")>[QACategories] = 40	

	<Xml.Serialization.XmlEnum("41")>[Series] = 41	

	<Xml.Serialization.XmlEnum("42")>[Origin] = 42	

	<Xml.Serialization.XmlEnum("43")>[GbosContainerCollection] = 43	

	<Xml.Serialization.XmlEnum("44")>[FreeViewPDF] = 44	

	<Xml.Serialization.XmlEnum("45")>[Subsite] = 45	

	<Xml.Serialization.XmlEnum("46")>[GeneralReference] = 46	

	<Xml.Serialization.XmlEnum("47")>[Reviews] = 47	

	<Xml.Serialization.XmlEnum("48")>[OUPSeries] = 48	

	<Xml.Serialization.XmlEnum("49")>[TocHeading] = 49	

	<Xml.Serialization.XmlEnum("50")>[JournalCollection] = 50	

	<Xml.Serialization.XmlEnum("51")>[Guideline] = 51	

	<Xml.Serialization.XmlEnum("52")>[KBARTJournalCollection] = 52	
End Enum

	''' <summary>
    '''Represents the types associated with LinkMembers 
    ''' </summary>
    ''' <remarks>Represents the types associated with LinkMembers</remarks>
Public Enum eLinkMemberType As Integer
	<Xml.Serialization.XmlEnum("1")>[section] = 1	
	<Xml.Serialization.XmlEnum("2")>[article] = 2	
	<Xml.Serialization.XmlEnum("3")>[multimedia] = 3	
	<Xml.Serialization.XmlEnum("4")>[issue] = 4	
	<Xml.Serialization.XmlEnum("5")>[url] = 5	
	<Xml.Serialization.XmlEnum("7")>[journal] = 7	
	<Xml.Serialization.XmlEnum("8")>[gbos] = 8	
	<Xml.Serialization.XmlEnum("9")>[book] = 9	
	<Xml.Serialization.XmlEnum("10")>[gboscontainer] = 10	
	<Xml.Serialization.XmlEnum("11")>[groups] = 11	
	<Xml.Serialization.XmlEnum("12")>[site] = 12	
	<Xml.Serialization.XmlEnum("13")>[category] = 13	
	<Xml.Serialization.XmlEnum("14")>[quiz] = 14	
	<Xml.Serialization.XmlEnum("15")>[question] = 15	
	<Xml.Serialization.XmlEnum("16")>[solquiz] = 16	
	<Xml.Serialization.XmlEnum("17")>[solquestion] = 17	
End Enum

	''' <summary>
    '''Represents the types associated with Multimedia 
    ''' </summary>
    ''' <remarks>Represents the types associated with Multimedia</remarks>
Public Enum eMultimediaType As Integer
	<Xml.Serialization.XmlEnum("1")>[image] = 1	
	<Xml.Serialization.XmlEnum("2")>[video] = 2	
	<Xml.Serialization.XmlEnum("3")>[audio] = 3	
	<Xml.Serialization.XmlEnum("4")>[flash] = 4	
	<Xml.Serialization.XmlEnum("5")>[podcast] = 5	
	<Xml.Serialization.XmlEnum("6")>[pdf] = 6	
	<Xml.Serialization.XmlEnum("7")>[excel] = 7	
	<Xml.Serialization.XmlEnum("8")>[powerpoint] = 8	
	<Xml.Serialization.XmlEnum("9")>[word] = 9	
	<Xml.Serialization.XmlEnum("10")>[zip] = 10	
	<Xml.Serialization.XmlEnum("11")>[videodatasupplement] = 11	
	<Xml.Serialization.XmlEnum("12")>[url] = 12	
	<Xml.Serialization.XmlEnum("13")>[html] = 13	
	<Xml.Serialization.XmlEnum("14")>[previewImage] = 14	
	<Xml.Serialization.XmlEnum("15")>[ignore] = 15	
	<Xml.Serialization.XmlEnum("16")>[Brightcove] = 16	
	<Xml.Serialization.XmlEnum("17")>[Amazon] = 17	
	<Xml.Serialization.XmlEnum("18")>[Vimeo] = 18	
	<Xml.Serialization.XmlEnum("19")>[YouTube] = 19	
	<Xml.Serialization.XmlEnum("20")>[html5] = 20	
	<Xml.Serialization.XmlEnum("21")>[Ooyala] = 21	
	<Xml.Serialization.XmlEnum("22")>[IssueCover] = 22	
	<Xml.Serialization.XmlEnum("23")>[Libsyn] = 23	
	<Xml.Serialization.XmlEnum("24")>[IssueCoverCaption] = 24	
	<Xml.Serialization.XmlEnum("25")>[IssueFrontMatter] = 25	
	<Xml.Serialization.XmlEnum("26")>[IssueBackMatter] = 26	
	<Xml.Serialization.XmlEnum("27")>[IssueEditorialBoard] = 27	
	<Xml.Serialization.XmlEnum("28")>[IssueToc] = 28	
	<Xml.Serialization.XmlEnum("29")>[IssueCoverFigure] = 29	
	<Xml.Serialization.XmlEnum("30")>[IssueAdvertising] = 30	
	<Xml.Serialization.XmlEnum("31")>[IssueAdministration] = 31	
	<Xml.Serialization.XmlEnum("32")>[sourceXML] = 32	
End Enum

	''' <summary>
    '''Represents the types associated with Quizzes 
    ''' </summary>
    ''' <remarks>Represents the types associated with Quizzes</remarks>
Public Enum eQuizType As Integer
	<Xml.Serialization.XmlEnum("1")>[QuarterlyCME] = 1	
	<Xml.Serialization.XmlEnum("2")>[MOCSelfAssessment] = 2	
	<Xml.Serialization.XmlEnum("3")>[SubspecialtyCME] = 3	
	<Xml.Serialization.XmlEnum("4")>[QuarterlyMOCCMEEvaluation] = 4	
	<Xml.Serialization.XmlEnum("5")>[SubspecialtyCMEEvaluation] = 5	
	<Xml.Serialization.XmlEnum("6")>[JBJSSharedOptionalEvaluation] = 6	
	<Xml.Serialization.XmlEnum("7")>[AJPCME] = 7	
	<Xml.Serialization.XmlEnum("8")>[AnnuallyCME] = 8	
	<Xml.Serialization.XmlEnum("9")>[SelfAssessmentBooks] = 9	
	<Xml.Serialization.XmlEnum("10")>[CMESharedOptionalEvaluation] = 10	
	<Xml.Serialization.XmlEnum("11")>[ACPCME] = 11	
	<Xml.Serialization.XmlEnum("12")>[AMACME] = 12	
	<Xml.Serialization.XmlEnum("13")>[CMEQuestionnaire] = 13	
	<Xml.Serialization.XmlEnum("14")>[CMEEvaluation] = 14	
End Enum

	''' <summary>
    '''Represents the types associated with Resources 
    ''' </summary>
    ''' <remarks>Represents the types associated with Resources</remarks>
Public Enum eResourceType As Integer
<Xml.Serialization.XmlEnum("0")> Undefined = 0 
	<Xml.Serialization.XmlEnum("1")>[Book] = 1	
	<Xml.Serialization.XmlEnum("2")>[Journal] = 2	
	<Xml.Serialization.XmlEnum("3")>[Article] = 3	
	<Xml.Serialization.XmlEnum("4")>[Multimedia] = 4	
	<Xml.Serialization.XmlEnum("5")>[Section] = 5	
	<Xml.Serialization.XmlEnum("6")>[Issue] = 6	
	<Xml.Serialization.XmlEnum("7")>[Collection] = 7	
	<Xml.Serialization.XmlEnum("8")>[Quiz] = 8	
	<Xml.Serialization.XmlEnum("9")>[ArticleClientType] = 9	
	<Xml.Serialization.XmlEnum("10")>[Conference] = 10	
	<Xml.Serialization.XmlEnum("11")>[ConferenceVolume] = 11	
	<Xml.Serialization.XmlEnum("12")>[Site] = 12	
	<Xml.Serialization.XmlEnum("13")>[Gbos] = 13	
	<Xml.Serialization.XmlEnum("14")>[SOLQuiz] = 14	
	<Xml.Serialization.XmlEnum("15")>[Cases] = 15	
	<Xml.Serialization.XmlEnum("16")>[MultimediaBook] = 16	
	<Xml.Serialization.XmlEnum("17")>[Calculators] = 17	
	<Xml.Serialization.XmlEnum("18")>[solCurriculaGroups] = 18	
	<Xml.Serialization.XmlEnum("19")>[GbosContainer] = 19	
	<Xml.Serialization.XmlEnum("20")>[SolAssignment] = 20	
	<Xml.Serialization.XmlEnum("21")>[Group] = 21	
	<Xml.Serialization.XmlEnum("22")>[SOLQuestion] = 22	
	<Xml.Serialization.XmlEnum("23")>[ClinicalQuery] = 23	
	<Xml.Serialization.XmlEnum("24")>[SolCourse] = 24	
	<Xml.Serialization.XmlEnum("25")>[OxMeta] = 25	
End Enum


	''' <summary>
    '''Represents the types associated with Sections 
    ''' </summary>
    ''' <remarks>Represents the types associated with Sections</remarks>
Public Enum eSectionType As Integer
	<Xml.Serialization.XmlEnum("1")>[Table] = 1	
	<Xml.Serialization.XmlEnum("2")>[Figure] = 2	
	<Xml.Serialization.XmlEnum("3")>[Abstract] = 3	
	<Xml.Serialization.XmlEnum("4")>[Authors] = 4	
	<Xml.Serialization.XmlEnum("5")>[References] = 5	
	<Xml.Serialization.XmlEnum("6")>[Chapter] = 6	
	<Xml.Serialization.XmlEnum("7")>[Section] = 7	
	<Xml.Serialization.XmlEnum("8")>[FrontNote] = 8	
	<Xml.Serialization.XmlEnum("9")>[Paragraph] = 9	
	<Xml.Serialization.XmlEnum("10")>[ArticleInfo] = 10	
	<Xml.Serialization.XmlEnum("11")>[Quiz] = 11	
	<Xml.Serialization.XmlEnum("12")>[Acknowledgements] = 12	
	<Xml.Serialization.XmlEnum("13")>[List] = 13	
	<Xml.Serialization.XmlEnum("14")>[Note] = 14	
	<Xml.Serialization.XmlEnum("15")>[Appendix] = 15	
	<Xml.Serialization.XmlEnum("16")>[AuthorNotes] = 16	
	<Xml.Serialization.XmlEnum("17")>[FootNote] = 17	
	<Xml.Serialization.XmlEnum("18")>[ArticleExtra] = 18	
	<Xml.Serialization.XmlEnum("19")>[AuthorExtra] = 19	
	<Xml.Serialization.XmlEnum("20")>[FrontExtra] = 20	
	<Xml.Serialization.XmlEnum("21")>[BackExtra] = 21	
	<Xml.Serialization.XmlEnum("22")>[PermissionStatement] = 22	
	<Xml.Serialization.XmlEnum("23")>[BoxSection] = 23	
	<Xml.Serialization.XmlEnum("24")>[Citation] = 24	
	<Xml.Serialization.XmlEnum("25")>[QuizQuestion] = 25	
	<Xml.Serialization.XmlEnum("26")>[QuizAnswer] = 26	
	<Xml.Serialization.XmlEnum("27")>[Glossary] = 27	
	<Xml.Serialization.XmlEnum("28")>[Response] = 28	
	<Xml.Serialization.XmlEnum("29")>[Epigraph] = 29	
	<Xml.Serialization.XmlEnum("30")>[BlockQuote] = 30	
	<Xml.Serialization.XmlEnum("31")>[Dialog] = 31	
	<Xml.Serialization.XmlEnum("32")>[CaseExample] = 32	
	<Xml.Serialization.XmlEnum("33")>[PubHistory] = 33	
	<Xml.Serialization.XmlEnum("34")>[AppendixGroup] = 34	
	<Xml.Serialization.XmlEnum("35")>[ArticleAppendix] = 35	
	<Xml.Serialization.XmlEnum("36")>[InlineTable] = 36	
	<Xml.Serialization.XmlEnum("37")>[Overview] = 37	
	<Xml.Serialization.XmlEnum("38")>[ChapNote] = 38	
	<Xml.Serialization.XmlEnum("39")>[DSMClassification] = 39	
	<Xml.Serialization.XmlEnum("40")>[FrontMatterPostTOC] = 40	
	<Xml.Serialization.XmlEnum("41")>[IndexByClass] = 41	
	<Xml.Serialization.XmlEnum("42")>[IntroChapter] = 42	
	<Xml.Serialization.XmlEnum("43")>[Workgroup] = 43	
	<Xml.Serialization.XmlEnum("44")>[Letters] = 44	
	<Xml.Serialization.XmlEnum("45")>[Poetry] = 45	
	<Xml.Serialization.XmlEnum("46")>[Review] = 46	
	<Xml.Serialization.XmlEnum("47")>[Contributor] = 47	
	<Xml.Serialization.XmlEnum("48")>[DisorderList] = 48	
	<Xml.Serialization.XmlEnum("49")>[BookPartIntro] = 49	
	<Xml.Serialization.XmlEnum("50")>[Synopsis] = 50	
	<Xml.Serialization.XmlEnum("51")>[FigGroup] = 51	
	<Xml.Serialization.XmlEnum("52")>[Precis] = 52	
	<Xml.Serialization.XmlEnum("53")>[MultimediaLegend] = 53	
	<Xml.Serialization.XmlEnum("54")>[FeaturedFigure] = 54	
	<Xml.Serialization.XmlEnum("55")>[MultimediaShortDescription] = 55	
	<Xml.Serialization.XmlEnum("56")>[SubHeading] = 56	
	<Xml.Serialization.XmlEnum("57")>[Attribution] = 57	
	<Xml.Serialization.XmlEnum("58")>[BookPart] = 58	
	<Xml.Serialization.XmlEnum("59")>[Vocabs] = 59	
	<Xml.Serialization.XmlEnum("60")>[Video] = 60	
	<Xml.Serialization.XmlEnum("61")>[BookPreface] = 61	
	<Xml.Serialization.XmlEnum("62")>[BookContributors] = 62	
	<Xml.Serialization.XmlEnum("63")>[Multimedia] = 63	
	<Xml.Serialization.XmlEnum("64")>[CaseQuestion] = 64	
	<Xml.Serialization.XmlEnum("65")>[CaseAnswer] = 65	
	<Xml.Serialization.XmlEnum("66")>[SOLQuiz] = 66	
	<Xml.Serialization.XmlEnum("67")>[QuizQuestionText] = 67	
	<Xml.Serialization.XmlEnum("68")>[QuizAnswerOption] = 68	
	<Xml.Serialization.XmlEnum("69")>[CorrespondenceInformation] = 69	
	<Xml.Serialization.XmlEnum("70")>[Dedication] = 70	
	<Xml.Serialization.XmlEnum("71")>[Foreword] = 71	
	<Xml.Serialization.XmlEnum("72")>[KeyPoint] = 72	
	<Xml.Serialization.XmlEnum("73")>[PeerReviewStatement] = 73	
	<Xml.Serialization.XmlEnum("74")>[CustomAnswer] = 74	
	<Xml.Serialization.XmlEnum("75")>[SigBlock] = 75	
	<Xml.Serialization.XmlEnum("76")>[FootNoteGroup] = 76	
	<Xml.Serialization.XmlEnum("77")>[ExecutiveSummary] = 77	
	<Xml.Serialization.XmlEnum("78")>[DefinitionList] = 78	
	<Xml.Serialization.XmlEnum("79")>[Audio] = 79	
	<Xml.Serialization.XmlEnum("80")>[QuizAnswerSet] = 80	
	<Xml.Serialization.XmlEnum("81")>[MediaJumpPoints] = 81	
	<Xml.Serialization.XmlEnum("82")>[Disclaimer] = 82	
	<Xml.Serialization.XmlEnum("83")>[MultimediaJumpPointHidden] = 83	
	<Xml.Serialization.XmlEnum("84")>[KeyPoints] = 84	
	<Xml.Serialization.XmlEnum("85")>[KeywordGroup] = 85	
	<Xml.Serialization.XmlEnum("86")>[ArxivReference] = 86	
	<Xml.Serialization.XmlEnum("87")>[TranslatedAbstract] = 87	
	<Xml.Serialization.XmlEnum("88")>[FormalStatement] = 88	
	<Xml.Serialization.XmlEnum("89")>[BackGlossary] = 89	
	<Xml.Serialization.XmlEnum("90")>[ProductReview] = 90	
	<Xml.Serialization.XmlEnum("91")>[Array] = 91	
	<Xml.Serialization.XmlEnum("92")>[TableGroup] = 92	
	<Xml.Serialization.XmlEnum("93")>[BackSection] = 93	
	<Xml.Serialization.XmlEnum("94")>[FrontNotes] = 94	
	<Xml.Serialization.XmlEnum("95")>[BackAcknowledgements] = 95	
	<Xml.Serialization.XmlEnum("96")>[BackAppendixGroup] = 96	
	<Xml.Serialization.XmlEnum("97")>[BackBio] = 97	
	<Xml.Serialization.XmlEnum("98")>[BackFootNoteGroup] = 98	
	<Xml.Serialization.XmlEnum("99")>[BackReferences] = 99	
	<Xml.Serialization.XmlEnum("100")>[BackNotes] = 100	
	<Xml.Serialization.XmlEnum("101")>[GraphicalAbstract] = 101	
End Enum

	''' <summary>
    '''Represents the types associated with Subscriptions 
    ''' </summary>
    ''' <remarks>Represents the types associated with Subscriptions</remarks>
Public Enum eSubscriptionType As Integer
	<Xml.Serialization.XmlEnum("1")>[regularpurchase] = 1	
	<Xml.Serialization.XmlEnum("2")>[freetrial] = 2	
	<Xml.Serialization.XmlEnum("3")>[ondemand] = 3	
	<Xml.Serialization.XmlEnum("4")>[specialoffer] = 4	
	<Xml.Serialization.XmlEnum("5")>[Complimentary] = 5	
	<Xml.Serialization.XmlEnum("6")>[BOM] = 6	
	<Xml.Serialization.XmlEnum("7")>[CNTL] = 7	
	<Xml.Serialization.XmlEnum("8")>[COMP] = 8	
	<Xml.Serialization.XmlEnum("9")>[PAID] = 9	
	<Xml.Serialization.XmlEnum("10")>[ADVCMP] = 10	
	<Xml.Serialization.XmlEnum("11")>[AOA] = 11	
	<Xml.Serialization.XmlEnum("12")>[SITE] = 12	
	<Xml.Serialization.XmlEnum("13")>[perpetual] = 13	
	<Xml.Serialization.XmlEnum("14")>[specialMembersSubscription] = 14	
End Enum


	''' <summary>
    '''Represents the types associated with Links
    ''' </summary>
    ''' <remarks>Represents the types associated with Links</remarks>
Public Enum eLinkType As Integer
	<Xml.Serialization.XmlEnum("1")>[related] = 1	
	<Xml.Serialization.XmlEnum("2")>[reference] = 2	
	<Xml.Serialization.XmlEnum("3")>[citation] = 3	
	<Xml.Serialization.XmlEnum("4")>[letterletter] = 4	
	<Xml.Serialization.XmlEnum("5")>[letterarticle] = 5	
	<Xml.Serialization.XmlEnum("6")>[supplementedissuesupplementalissue] = 6	
	<Xml.Serialization.XmlEnum("7")>[correction] = 7	
	<Xml.Serialization.XmlEnum("8")>[EditorsChoice] = 8	
	<Xml.Serialization.XmlEnum("9")>[commentary] = 9	
	<Xml.Serialization.XmlEnum("10")>[letter] = 10	
	<Xml.Serialization.XmlEnum("11")>[podcastarticle] = 11	
	<Xml.Serialization.XmlEnum("12")>[podcastissue] = 12	
	<Xml.Serialization.XmlEnum("13")>[PatientSummaryArticle] = 13	
	<Xml.Serialization.XmlEnum("14")>[multimediaarticle] = 14	
	<Xml.Serialization.XmlEnum("15")>[multimediaissue] = 15	
	<Xml.Serialization.XmlEnum("16")>[multimediajournal] = 16	
	<Xml.Serialization.XmlEnum("17")>[companion] = 17	
	<Xml.Serialization.XmlEnum("18")>[erratum] = 18	
	<Xml.Serialization.XmlEnum("19")>[retractedarticle] = 19	
	<Xml.Serialization.XmlEnum("20")>[multimediaPDF] = 20	
	<Xml.Serialization.XmlEnum("21")>[viewincontext] = 21	
	<Xml.Serialization.XmlEnum("22")>[relatedQAResource] = 22	
	<Xml.Serialization.XmlEnum("23")>[multimediaBook] = 23	
	<Xml.Serialization.XmlEnum("24")>[relatedSOLQuiz] = 24	
	<Xml.Serialization.XmlEnum("25")>[videointerview] = 25	
	<Xml.Serialization.XmlEnum("26")>[interactive] = 26	
	<Xml.Serialization.XmlEnum("27")>[journalclubslides] = 27	
	<Xml.Serialization.XmlEnum("28")>[sharedSOLQuizQuestion] = 28	
	<Xml.Serialization.XmlEnum("29")>[TextBookUpdates] = 29	
	<Xml.Serialization.XmlEnum("30")>[relatedInstructorContent] = 30	
	<Xml.Serialization.XmlEnum("31")>[TextbookUpdateContent] = 31	
	<Xml.Serialization.XmlEnum("32")>[QuickTestContent] = 32	
	<Xml.Serialization.XmlEnum("33")>[Translation] = 33	
	<Xml.Serialization.XmlEnum("34")>[EducationGuides] = 34	
	<Xml.Serialization.XmlEnum("35")>[Podcasts] = 35	
	<Xml.Serialization.XmlEnum("36")>[Calculator] = 36	
	<Xml.Serialization.XmlEnum("37")>[WorkSheets] = 37	
	<Xml.Serialization.XmlEnum("38")>[subsumedby] = 38	
	<Xml.Serialization.XmlEnum("39")>[relatedCaseResource] = 39	
	<Xml.Serialization.XmlEnum("40")>[multimediagbos] = 40	
	<Xml.Serialization.XmlEnum("41")>[update] = 41	
	<Xml.Serialization.XmlEnum("42")>[adaptedsource] = 42	
	<Xml.Serialization.XmlEnum("43")>[deeperinfo] = 43	
	<Xml.Serialization.XmlEnum("44")>[embedcontainer] = 44	
	<Xml.Serialization.XmlEnum("45")>[embedconsumer] = 45	
	<Xml.Serialization.XmlEnum("46")>[ExpressionOfConcern] = 46	
	<Xml.Serialization.XmlEnum("47")>[retractedreplacedarticle] = 47	
	<Xml.Serialization.XmlEnum("48")>[updatechapter] = 48	
End Enum

	''' <summary>
    '''Represents the types associated with Links
    ''' </summary>
    ''' <remarks>Represents the types associated with Links</remarks>
Public Enum eArticleRootType As Integer
	<Xml.Serialization.XmlEnum("1")>[Article] = 1	
	<Xml.Serialization.XmlEnum("2")>[Quiz] = 2	
	<Xml.Serialization.XmlEnum("3")>[Letter] = 3	
	<Xml.Serialization.XmlEnum("4")>[Correction] = 4	
	<Xml.Serialization.XmlEnum("5")>[Filler] = 5	
	<Xml.Serialization.XmlEnum("6")>[Wrapper] = 6	
	<Xml.Serialization.XmlEnum("7")>[Newsletter] = 7	
	<Xml.Serialization.XmlEnum("8")>[Proceeding] = 8	
End Enum

	''' <summary>
    '''Represents the types associated with Links
    ''' </summary>
    ''' <remarks>Represents the types associated with Links</remarks>
Public Enum eUserCommentStatusType As Integer
	<Xml.Serialization.XmlEnum("1")>[submitted] = 1	
	<Xml.Serialization.XmlEnum("2")>[published] = 2	
	<Xml.Serialization.XmlEnum("3")>[deleted] = 3	
End Enum

	''' <summary>
    '''Represents the types associated with Alerts
    ''' </summary>
    ''' <remarks>Represents the types associated with Links</remarks>
Public Enum eAlertTypes As Integer
	<Xml.Serialization.XmlEnum("1")>[Article] = 1	
	<Xml.Serialization.XmlEnum("2")>[Chapter] = 2	
	<Xml.Serialization.XmlEnum("3")>[PublishAheadofPrint] = 3	
	<Xml.Serialization.XmlEnum("4")>[Collection] = 4	
	<Xml.Serialization.XmlEnum("5")>[LatestIssue] = 5	
	<Xml.Serialization.XmlEnum("6")>[Search] = 6	
	<Xml.Serialization.XmlEnum("7")>[NewBookEdition] = 7	
	<Xml.Serialization.XmlEnum("8")>[PublisherMarketingOptIn] = 8	
	<Xml.Serialization.XmlEnum("10")>[NewQuiz] = 10	
	<Xml.Serialization.XmlEnum("11")>[ExpiringQuiz] = 11	
	<Xml.Serialization.XmlEnum("12")>[CompletedQuiz] = 12	
	<Xml.Serialization.XmlEnum("13")>[CME] = 13	
	<Xml.Serialization.XmlEnum("14")>[ExpiringIndividualSubscriptions] = 14	
	<Xml.Serialization.XmlEnum("15")>[ExpiringInstitutionalSubscriptions] = 15	
	<Xml.Serialization.XmlEnum("16")>[PasswordReset] = 16	
	<Xml.Serialization.XmlEnum("17")>[Proceeding] = 17	
	<Xml.Serialization.XmlEnum("18")>[UserAccountCreation] = 18	
	<Xml.Serialization.XmlEnum("19")>[InstitutionCreation] = 19	
	<Xml.Serialization.XmlEnum("20")>[CounterReport] = 20	
	<Xml.Serialization.XmlEnum("21")>[NewContentAlertForArticles] = 21	
	<Xml.Serialization.XmlEnum("22")>[ExpiringTokens] = 22	
	<Xml.Serialization.XmlEnum("23")>[Continuouspublishingalerts] = 23	
	<Xml.Serialization.XmlEnum("24")>[LatestBook] = 24	
	<Xml.Serialization.XmlEnum("25")>[InstitutionTokensExpiration] = 25	
	<Xml.Serialization.XmlEnum("26")>[SolAssignment] = 26	
	<Xml.Serialization.XmlEnum("27")>[SyncOnlyAlert] = 27	
	<Xml.Serialization.XmlEnum("28")>[ArticleGroups] = 28	
	<Xml.Serialization.XmlEnum("29")>[WeeklyeTOC] = 29	
	<Xml.Serialization.XmlEnum("30")>[NewJournalContent] = 30	
	<Xml.Serialization.XmlEnum("31")>[AuthorTollFreeLink] = 31	
	<Xml.Serialization.XmlEnum("32")>[AllContent] = 32	
	<Xml.Serialization.XmlEnum("33")>[TaxonomyCollectionsSearch] = 33	
End Enum

	''' <summary>
    '''Represents the types associated with Address
    ''' </summary>
    ''' <remarks>Represents the types associated with Address</remarks>
Public Enum eAddressTypes As Integer
	<Xml.Serialization.XmlEnum("1")>[Shipping] = 1	
	<Xml.Serialization.XmlEnum("2")>[Billing] = 2	
End Enum

	''' <summary>
    '''Represents the types associated with Products
    ''' </summary>
    ''' <remarks>Represents the types associated with Products</remarks>
Public Enum eProductTypes As Integer
	<Xml.Serialization.XmlEnum("1")>[Individual] = 1	
	<Xml.Serialization.XmlEnum("2")>[Institutional] = 2	
	<Xml.Serialization.XmlEnum("3")>[OnDemand] = 3	
	<Xml.Serialization.XmlEnum("4")>[All] = 4	
	<Xml.Serialization.XmlEnum("5")>[OnDemandTemplate] = 5	
	<Xml.Serialization.XmlEnum("7")>[SpecialMembershipBasedProduct] = 7	
	<Xml.Serialization.XmlEnum("8")>[ProductBuilder] = 8	
End Enum

	''' <summary>
    '''Represents the types associated with Product Terms
    ''' </summary>
    ''' <remarks>Represents the types associated with Product Terms</remarks>
Public Enum eProductTermsType As Integer
	<Xml.Serialization.XmlEnum("1")>[Hours] = 1	
	<Xml.Serialization.XmlEnum("2")>[Days] = 2	
	<Xml.Serialization.XmlEnum("3")>[Months] = 3	
	<Xml.Serialization.XmlEnum("4")>[Years] = 4	
	<Xml.Serialization.XmlEnum("5")>[Unlimited] = 5	
End Enum


	''' <summary>
    '''Represents the stages associated with user quizzes
    ''' </summary>
    ''' <remarks>Represents the stages associated with user quizzes</remarks>
Public Enum eUserQuizStage As Integer
	<Xml.Serialization.XmlEnum("1")>[InProgress] = 1	
	<Xml.Serialization.XmlEnum("2")>[CompletedCreditUnearned] = 2	
	<Xml.Serialization.XmlEnum("3")>[CompletedCreditEarned] = 3	
	<Xml.Serialization.XmlEnum("4")>[SubmittedEvaluation] = 4	
	<Xml.Serialization.XmlEnum("5")>[CompletedForPractice] = 5	
End Enum

	''' <summary>
    '''Represents the user CME credit types
    ''' </summary>
    ''' <remarks>Represents the user CME credit types</remarks>
Public Enum eCMECreditType As Integer
	<Xml.Serialization.XmlEnum("1")>[AMAPRACategory1Credits] = 1	
	<Xml.Serialization.XmlEnum("2")>[MOCSAECredits] = 2	
	<Xml.Serialization.XmlEnum("3")>[ContinuingEducation] = 3	
	<Xml.Serialization.XmlEnum("4")>[ClinicalQueryCMECredits] = 4	
End Enum


	''' <summary>
    '''Represents the user CME credit types
    ''' </summary>
    ''' <remarks>Represents the user CME credit types</remarks>
Public Enum eGroupType As Integer
	<Xml.Serialization.XmlEnum("1")>[PaPArticles] = 1	
	<Xml.Serialization.XmlEnum("2")>[Journals] = 2	
	<Xml.Serialization.XmlEnum("3")>[Books] = 3	
	<Xml.Serialization.XmlEnum("4")>[BookParts] = 4	
	<Xml.Serialization.XmlEnum("5")>[MultimediaGroup] = 5	
	<Xml.Serialization.XmlEnum("6")>[Retraction] = 6	
	<Xml.Serialization.XmlEnum("7")>[JAMArticles] = 7	
	<Xml.Serialization.XmlEnum("8")>[GBOS] = 8	
	<Xml.Serialization.XmlEnum("9")>[BookUpdates] = 9	
	<Xml.Serialization.XmlEnum("10")>[MGHTEBPPUpdates] = 10	
	<Xml.Serialization.XmlEnum("11")>[Cases] = 11	
	<Xml.Serialization.XmlEnum("12")>[Algorithms] = 12	
	<Xml.Serialization.XmlEnum("13")>[QAResource] = 13	
	<Xml.Serialization.XmlEnum("14")>[PatientEducationHandouts] = 14	
	<Xml.Serialization.XmlEnum("15")>[CMEStateDegree] = 15	
	<Xml.Serialization.XmlEnum("16")>[CategorySets] = 16	
	<Xml.Serialization.XmlEnum("17")>[Subjects] = 17	
	<Xml.Serialization.XmlEnum("18")>[Calculator] = 18	
	<Xml.Serialization.XmlEnum("19")>[EmailAFriend] = 19	
	<Xml.Serialization.XmlEnum("20")>[OnlineOnly] = 20	
	<Xml.Serialization.XmlEnum("21")>[RotatingFeatureImageEligible] = 21	
	<Xml.Serialization.XmlEnum("22")>[RotatingFeatureImageCurrent] = 22	
	<Xml.Serialization.XmlEnum("23")>[CMEEligible] = 23	
	<Xml.Serialization.XmlEnum("25")>[Images] = 25	
	<Xml.Serialization.XmlEnum("26")>[Reviews] = 26	
	<Xml.Serialization.XmlEnum("27")>[ExternalLinks] = 27	
	<Xml.Serialization.XmlEnum("28")>[CEU] = 28	
	<Xml.Serialization.XmlEnum("29")>[ProgressiveQuizzes] = 29	
End Enum


	''' <summary>
    '''Represents the types of Self-Serve Content (and therefore how a piece of Self-Serve Content is used)
    ''' </summary>
    ''' <remarks>Represents the types of Self-Serve Content (and therefore how a piece of Self-Serve Content is used)</remarks>
Public Enum eSelfServeContentType As Integer
	<Xml.Serialization.XmlEnum("1")>[DropIn] = 1	
	<Xml.Serialization.XmlEnum("2")>[Page] = 2	
	<Xml.Serialization.XmlEnum("3")>[Email] = 3	
	<Xml.Serialization.XmlEnum("4")>[SilverchairInternalOnly] = 4	
End Enum





	''' <summary>
    '''Represents the types of Sites
    ''' </summary>
    ''' <remarks>Represents the types of Sites</remarks>

Public Enum eSiteType As Integer
	<Xml.Serialization.XmlEnum("1")>[Umbrella] = 1	
	<Xml.Serialization.XmlEnum("2")>[Micro] = 2	
	<Xml.Serialization.XmlEnum("5")>[SharedMenu] = 5	
	<Xml.Serialization.XmlEnum("6")>[ThirdPartySite] = 6	
End Enum



	''' <summary>
	'''Represents types of actions to be controlled by resourceActionPermissions
	''' </summary>
	''' <remarks>Represents types of actions to be controlled by resourceActionPermissions</remarks>

Public Enum eResourceActionType As Integer
	<Xml.Serialization.XmlEnum("1")>[ShowComments] = 1	
	<Xml.Serialization.XmlEnum("2")>[SubmitComments] = 2	
End Enum


	''' <summary>
	'''Represents types of Author Types
	''' </summary>
	''' <remarks>Author Types</remarks>

Public Enum eAuthorType As Integer
	<Xml.Serialization.XmlEnum("1")>[IndividualAuthor] = 1	
	<Xml.Serialization.XmlEnum("2")>[IndividualCollaborativeGroup] = 2	
	<Xml.Serialization.XmlEnum("3")>[Anonymous] = 3	
	<Xml.Serialization.XmlEnum("4")>[Sponsor] = 4	
	<Xml.Serialization.XmlEnum("5")>[IndividualCollaborativeGroupMember] = 5	
	<Xml.Serialization.XmlEnum("6")>[NonBylineAuthor] = 6	
	<Xml.Serialization.XmlEnum("7")>[OnBehalfOf] = 7	
	<Xml.Serialization.XmlEnum("8")>[Editor] = 8	
End Enum
	

	''' <summary>
	'''Represents types of Billing Status Types
	''' </summary>
	''' <remarks>Billing Status Types</remarks>

Public Enum eBillingStatusType As Integer
	<Xml.Serialization.XmlEnum("3")>[Billed] = 3	
	<Xml.Serialization.XmlEnum("5")>[CancellationCredit] = 5	
	<Xml.Serialization.XmlEnum("4")>[Complimentary] = 4	
	<Xml.Serialization.XmlEnum("9")>[N] = 9	
	<Xml.Serialization.XmlEnum("2")>[OnApproval] = 2	
	<Xml.Serialization.XmlEnum("6")>[PaidUp] = 6	
	<Xml.Serialization.XmlEnum("7")>[ReinstatedSubscription] = 7	
End Enum


	''' <summary>
	'''Represents types of Subscription Status Types
	''' </summary>
	''' <remarks>Subscription Status Types</remarks>

Public Enum eSubscriptionStatusType As Integer
	<Xml.Serialization.XmlEnum("19")>[ActivationCandidate] = 19	
	<Xml.Serialization.XmlEnum("6")>[BillingSuspended] = 6	
	<Xml.Serialization.XmlEnum("20")>[CancellationCandidate] = 20	
	<Xml.Serialization.XmlEnum("13")>[ControlledReceiving] = 13	
	<Xml.Serialization.XmlEnum("7")>[CustomerCanceled] = 7	
	<Xml.Serialization.XmlEnum("10")>[DelayedEntry] = 10	
	<Xml.Serialization.XmlEnum("8")>[Expired] = 8	
	<Xml.Serialization.XmlEnum("18")>[FutureStart] = 18	
	<Xml.Serialization.XmlEnum("15")>[IndefiniteSuspension] = 15	
	<Xml.Serialization.XmlEnum("11")>[NonPayCanceled] = 11	
	<Xml.Serialization.XmlEnum("12")>[PerpetualSubscription] = 12	
	<Xml.Serialization.XmlEnum("9")>[Proforma] = 9	
	<Xml.Serialization.XmlEnum("14")>[RegularReceiving] = 14	
	<Xml.Serialization.XmlEnum("16")>[TemporarySuspension] = 16	
	<Xml.Serialization.XmlEnum("17")>[Undeliverable] = 17	
End Enum


	''' <summary>
	'''Represents types of Agreement Status Types
	''' </summary>
	''' <remarks>Agreement Status Types</remarks>

Public Enum eAgreementStatusType As Integer
	<Xml.Serialization.XmlEnum("1")>[Active] = 1	
	<Xml.Serialization.XmlEnum("2")>[BillingSuspended] = 2	
	<Xml.Serialization.XmlEnum("3")>[Cancelled] = 3	
	<Xml.Serialization.XmlEnum("4")>[Expired] = 4	
	<Xml.Serialization.XmlEnum("10")>[ExtensionDays] = 10	
	<Xml.Serialization.XmlEnum("16")>[Gracing] = 16	
	<Xml.Serialization.XmlEnum("14")>[L] = 14	
	<Xml.Serialization.XmlEnum("6")>[NonpayCancelled] = 6	
	<Xml.Serialization.XmlEnum("11")>[NotReleased] = 11	
	<Xml.Serialization.XmlEnum("13")>[Oldversion] = 13	
	<Xml.Serialization.XmlEnum("5")>[PreFreeDays] = 5	
	<Xml.Serialization.XmlEnum("7")>[Proforma] = 7	
	<Xml.Serialization.XmlEnum("15")>[Q] = 15	
	<Xml.Serialization.XmlEnum("8")>[Reversed] = 8	
	<Xml.Serialization.XmlEnum("9")>[Suspended] = 9	
	<Xml.Serialization.XmlEnum("12")>[Waiting] = 12	
End Enum



	''' <summary>
	'''Represents types of tokens
	''' </summary>
	''' <remarks>Token Types</remarks>

Public Enum eTokenTypes As Integer
	<Xml.Serialization.XmlEnum("1")>[CME] = 1	
	<Xml.Serialization.XmlEnum("2")>[PayPerView] = 2	
End Enum



	''' <summary>
	''' Contains the IDs of each client 
	''' </summary>
	''' <remarks>Client IDs</remarks>

Public Enum eClients As Integer
	<Xml.Serialization.XmlEnum("11")>[TheMcGrawHillCompanies] = 11	
	<Xml.Serialization.XmlEnum("1")>[Silverchair] = 1	
	<Xml.Serialization.XmlEnum("2")>[TheJournalofBoneandJointSurgery] = 2	
	<Xml.Serialization.XmlEnum("3")>[AmericanMedicalAssociation] = 3	
	<Xml.Serialization.XmlEnum("4")>[AmericanPsychiatricAssociation] = 4	
	<Xml.Serialization.XmlEnum("6")>[AmericanPharmacistsAssociation] = 6	
	<Xml.Serialization.XmlEnum("7")>[AmericanCollegeofPhysicians] = 7	
	<Xml.Serialization.XmlEnum("8")>[InternationalSocietyforOpticsandPhotonics] = 8	
	<Xml.Serialization.XmlEnum("9")>[AmericanCollegeofChestPhysicians] = 9	
	<Xml.Serialization.XmlEnum("10")>[JournaloftheAmericanCollegeofCardiology] = 10	
	<Xml.Serialization.XmlEnum("11")>[McGrawHillEducation] = 11	
	<Xml.Serialization.XmlEnum("12")>[AmericanSocietyofMechanicalEngineers] = 12	
	<Xml.Serialization.XmlEnum("13")>[AmericanSpeechLanguageHearingAssociation] = 13	
	<Xml.Serialization.XmlEnum("14")>[WoltersKluwer] = 14	
	<Xml.Serialization.XmlEnum("15")>[AmericanOccupationalTherapyAssociation] = 15	
	<Xml.Serialization.XmlEnum("16")>[TexasPete] = 16	
	<Xml.Serialization.XmlEnum("17")>[AmericanAcademyofPediatrics] = 17	
	<Xml.Serialization.XmlEnum("18")>[TheAmericanSocietyofAnesthesiologists] = 18	
	<Xml.Serialization.XmlEnum("19")>[TheAssociationforResearchinVisionandOphthalmology] = 19	
	<Xml.Serialization.XmlEnum("20")>[AmericanOsteopathicAssociation] = 20	
	<Xml.Serialization.XmlEnum("21")>[RoyalCollegeofPaediatricsandChildHealth] = 21	
	<Xml.Serialization.XmlEnum("22")>[Narnia] = 22	
	<Xml.Serialization.XmlEnum("23")>[AmericanAcademyofDermatology] = 23	
	<Xml.Serialization.XmlEnum("24")>[GeoScienceWorld] = 24	
	<Xml.Serialization.XmlEnum("25")>[SilverchairDemoClient] = 25	
	<Xml.Serialization.XmlEnum("26")>[DukeUniversityPress] = 26	
End Enum


	''' <summary>
	''' Represents types of Institution Federations
	''' </summary>

Public Enum eInstitutionFederationType As Integer
	<Xml.Serialization.XmlEnum("1")>[Shibboleth] = 1	
End Enum


	''' <summary>
	''' Contains the IDs of each Payment Method
	''' </summary>
	''' <remarks></remarks>

Public Enum ePaymentMethods As Integer
	<Xml.Serialization.XmlEnum("1")>[Visa] = 1	
	<Xml.Serialization.XmlEnum("2")>[MasterCard] = 2	
	<Xml.Serialization.XmlEnum("3")>[Discover] = 3	
	<Xml.Serialization.XmlEnum("4")>[AmericanExpress] = 4	
End Enum


	''' <summary>
	''' Contains the IDs of each Payment Method Type
	''' </summary>
	''' <remarks></remarks>

Public Enum ePaymentMethodTypes As Integer
	<Xml.Serialization.XmlEnum("1")>[CreditCard] = 1	
End Enum


	''' <summary>
	''' Represents the statuses available to e.g. ConfrenceVolume.OpenStatus
	''' </summary>
	''' <remarks></remarks>

Public Enum eOpenStatus As Integer
	<Xml.Serialization.XmlEnum("1")>[Open] = 1	
	<Xml.Serialization.XmlEnum("2")>[Closed] = 2	
End Enum


	''' <summary>
	''' These are the types of client APIs. 3rd-party service providers.
	''' </summary>
	''' <remarks></remarks>

Public Enum eClientAPIKeyTypes As Integer
	<Xml.Serialization.XmlEnum("1")>[Contactology] = 1	
End Enum


	''' <summary>
	''' These are the types of Alert Trigger Statuses
	''' </summary>
	''' <remarks></remarks>

Public Enum eAlertTriggerStatus As Integer
	<Xml.Serialization.XmlEnum("1")>[Triggered] = 1	
	<Xml.Serialization.XmlEnum("2")>[Testing] = 2	
	<Xml.Serialization.XmlEnum("3")>[Sent] = 3	
	<Xml.Serialization.XmlEnum("4")>[Deleted] = 4	
End Enum


	''' <summary>
	''' These are the types of token Configuration Types
	''' </summary>
	''' <remarks></remarks>

Public Enum etokenConfigurationType As Integer
	<Xml.Serialization.XmlEnum("1")>[RedeemedContentExpiration] = 1	
	<Xml.Serialization.XmlEnum("2")>[NumberOfTokensPerResourceType] = 2	
	<Xml.Serialization.XmlEnum("3")>[TokensExpire] = 3	
	<Xml.Serialization.XmlEnum("4")>[NumberOfTokensLeft] = 4	
End Enum


	''' <summary>
	''' These are the Pages for Configuration
	''' </summary>
	''' <remarks></remarks>

Public Enum eConfigPages As Integer
	<Xml.Serialization.XmlEnum("1")>[AboutSearch] = 1	
	<Xml.Serialization.XmlEnum("3")>[ACCLogin] = 3	
	<Xml.Serialization.XmlEnum("2")>[AccessDevelopingCountry] = 2	
	<Xml.Serialization.XmlEnum("4")>[AdvancedSearch] = 4	
	<Xml.Serialization.XmlEnum("5")>[AdvancedSearchResults] = 5	
	<Xml.Serialization.XmlEnum("6")>[Advertisers] = 6	
	<Xml.Serialization.XmlEnum("9")>[AJPAbout] = 9	
	<Xml.Serialization.XmlEnum("7")>[AJPAuthorsReviewers] = 7	
	<Xml.Serialization.XmlEnum("8")>[AJPIFORA] = 8	
	<Xml.Serialization.XmlEnum("10")>[AJPInAdvance] = 10	
	<Xml.Serialization.XmlEnum("133")>[AMMOArticle] = 133	
	<Xml.Serialization.XmlEnum("13")>[APAbout] = 13	
	<Xml.Serialization.XmlEnum("11")>[APAuthorsReviewers] = 11	
	<Xml.Serialization.XmlEnum("12")>[APIFORA] = 12	
	<Xml.Serialization.XmlEnum("14")>[Article] = 14	
	<Xml.Serialization.XmlEnum("15")>[ArticleReports] = 15	
	<Xml.Serialization.XmlEnum("17")>[AthensProtectedResource] = 17	
	<Xml.Serialization.XmlEnum("18")>[Audio] = 18	
	<Xml.Serialization.XmlEnum("16")>[AuthenticationHandler] = 16	
	<Xml.Serialization.XmlEnum("19")>[Book] = 19	
	<Xml.Serialization.XmlEnum("20")>[Books] = 20	
	<Xml.Serialization.XmlEnum("21")>[BrowseBooks] = 21	
	<Xml.Serialization.XmlEnum("22")>[Calculators] = 22	
	<Xml.Serialization.XmlEnum("23")>[Carousel] = 23	
	<Xml.Serialization.XmlEnum("24")>[Cases] = 24	
	<Xml.Serialization.XmlEnum("135")>[Chapter] = 135	
	<Xml.Serialization.XmlEnum("25")>[CitationSearchResults] = 25	
	<Xml.Serialization.XmlEnum("26")>[CME] = 26	
	<Xml.Serialization.XmlEnum("27")>[CMEActivity] = 27	
	<Xml.Serialization.XmlEnum("28")>[CMEPerformance] = 28	
	<Xml.Serialization.XmlEnum("29")>[CMEQuiz] = 29	
	<Xml.Serialization.XmlEnum("30")>[CMETest] = 30	
	<Xml.Serialization.XmlEnum("31")>[Collection] = 31	
	<Xml.Serialization.XmlEnum("32")>[Collections] = 32	
	<Xml.Serialization.XmlEnum("33")>[ConferenceProceedings] = 33	
	<Xml.Serialization.XmlEnum("34")>[Content] = 34	
	<Xml.Serialization.XmlEnum("35")>[CoverArt] = 35	
	<Xml.Serialization.XmlEnum("36")>[CoverCollection] = 36	
	<Xml.Serialization.XmlEnum("37")>[DownloadCitation] = 37	
	<Xml.Serialization.XmlEnum("136")>[Drug] = 136	
	<Xml.Serialization.XmlEnum("38")>[Drugs] = 38	
	<Xml.Serialization.XmlEnum("39")>[DSMLibrary] = 39	
	<Xml.Serialization.XmlEnum("40")>[DSMPreviousEditions] = 40	
	<Xml.Serialization.XmlEnum("41")>[eFirst] = 41	
	<Xml.Serialization.XmlEnum("42")>[Error404] = 42	
	<Xml.Serialization.XmlEnum("45")>[FocusAbout] = 45	
	<Xml.Serialization.XmlEnum("43")>[FocusAuthorsReviewers] = 43	
	<Xml.Serialization.XmlEnum("44")>[FocusIFORA] = 44	
	<Xml.Serialization.XmlEnum("46")>[ForAuthors] = 46	
	<Xml.Serialization.XmlEnum("47")>[ForPatients] = 47	
	<Xml.Serialization.XmlEnum("92")>[ForgotPassword] = 92	
	<Xml.Serialization.XmlEnum("48")>[Glossary] = 48	
	<Xml.Serialization.XmlEnum("49")>[Guideline] = 49	
	<Xml.Serialization.XmlEnum("50")>[Guidelines] = 50	
	<Xml.Serialization.XmlEnum("51")>[HealthCheck] = 51	
	<Xml.Serialization.XmlEnum("52")>[IEDetect] = 52	
	<Xml.Serialization.XmlEnum("58")>[IntheClinicSlideset] = 58	
	<Xml.Serialization.XmlEnum("53")>[Index] = 53	
	<Xml.Serialization.XmlEnum("54")>[IndexNew] = 54	
	<Xml.Serialization.XmlEnum("55")>[IndexSJ] = 55	
	<Xml.Serialization.XmlEnum("56")>[InstitutionalSignIn] = 56	
	<Xml.Serialization.XmlEnum("57")>[InteractiveMultimedia] = 57	
	<Xml.Serialization.XmlEnum("59")>[Issue] = 59	
	<Xml.Serialization.XmlEnum("60")>[Issues] = 60	
	<Xml.Serialization.XmlEnum("61")>[Jobs] = 61	
	<Xml.Serialization.XmlEnum("62")>[Journal] = 62	
	<Xml.Serialization.XmlEnum("63")>[JournalClub] = 63	
	<Xml.Serialization.XmlEnum("64")>[Journals] = 64	
	<Xml.Serialization.XmlEnum("65")>[MediaJournalists] = 65	
	<Xml.Serialization.XmlEnum("66")>[MeetingAbstracts] = 66	
	<Xml.Serialization.XmlEnum("132")>[MobileArticle] = 132	
	<Xml.Serialization.XmlEnum("134")>[MobileIssue] = 134	
	<Xml.Serialization.XmlEnum("67")>[Multimedia] = 67	
	<Xml.Serialization.XmlEnum("68")>[MultimediaOLD] = 68	
	<Xml.Serialization.XmlEnum("69")>[MultimediaPlayer] = 69	
	<Xml.Serialization.XmlEnum("70")>[NeuroAuthorsReviewers] = 70	
	<Xml.Serialization.XmlEnum("71")>[NeuroIFORA] = 71	
	<Xml.Serialization.XmlEnum("72")>[NewsArticle] = 72	
	<Xml.Serialization.XmlEnum("76")>[NewsLetterSignup] = 76	
	<Xml.Serialization.XmlEnum("77")>[NewsMedia] = 77	
	<Xml.Serialization.XmlEnum("73")>[NewsletterArchive] = 73	
	<Xml.Serialization.XmlEnum("74")>[NewsletterArticle] = 74	
	<Xml.Serialization.XmlEnum("75")>[NewsletterHome] = 75	
	<Xml.Serialization.XmlEnum("78")>[NPAbout] = 78	
	<Xml.Serialization.XmlEnum("79")>[OnlineFirst] = 79	
	<Xml.Serialization.XmlEnum("80")>[OptOut] = 80	
	<Xml.Serialization.XmlEnum("82")>[Patient] = 82	
	<Xml.Serialization.XmlEnum("81")>[PatientInformation] = 81	
	<Xml.Serialization.XmlEnum("83")>[Patients] = 83	
	<Xml.Serialization.XmlEnum("84")>[PersonalSignIn] = 84	
	<Xml.Serialization.XmlEnum("85")>[PNAbout] = 85	
	<Xml.Serialization.XmlEnum("86")>[PNHome] = 86	
	<Xml.Serialization.XmlEnum("87")>[Podcasts] = 87	
	<Xml.Serialization.XmlEnum("88")>[PodcastsArchive] = 88	
	<Xml.Serialization.XmlEnum("89")>[PodcastsFAQ] = 89	
	<Xml.Serialization.XmlEnum("90")>[PopupAdditionalContent] = 90	
	<Xml.Serialization.XmlEnum("91")>[PopupDataSupplement] = 91	
	<Xml.Serialization.XmlEnum("105")>[PowerPointDownloads] = 105	
	<Xml.Serialization.XmlEnum("106")>[PowerPointTest] = 106	
	<Xml.Serialization.XmlEnum("93")>[Proceeding] = 93	
	<Xml.Serialization.XmlEnum("94")>[ProceedingBrowse] = 94	
	<Xml.Serialization.XmlEnum("99")>[PSAbout] = 99	
	<Xml.Serialization.XmlEnum("95")>[PSAuthorsReviewers] = 95	
	<Xml.Serialization.XmlEnum("96")>[PSIFORA] = 96	
	<Xml.Serialization.XmlEnum("100")>[PSInAdvance] = 100	
	<Xml.Serialization.XmlEnum("97")>[PSJobs] = 97	
	<Xml.Serialization.XmlEnum("98")>[PSJobsListing] = 98	
	<Xml.Serialization.XmlEnum("104")>[PublicAccessPolicy] = 104	
	<Xml.Serialization.XmlEnum("101")>[PyschNewsJobListing] = 101	
	<Xml.Serialization.XmlEnum("102")>[PyschNewsJobs] = 102	
	<Xml.Serialization.XmlEnum("103")>[PyschNewsLetters] = 103	
	<Xml.Serialization.XmlEnum("107")>[QuizPerformance] = 107	
	<Xml.Serialization.XmlEnum("108")>[Readers] = 108	
	<Xml.Serialization.XmlEnum("109")>[RedirectResolverTest] = 109	
	<Xml.Serialization.XmlEnum("110")>[ResetPassword] = 110	
	<Xml.Serialization.XmlEnum("111")>[ResidentsJournal] = 111	
	<Xml.Serialization.XmlEnum("112")>[RSS] = 112	
	<Xml.Serialization.XmlEnum("113")>[RSSFeeds] = 113	
	<Xml.Serialization.XmlEnum("114")>[SavedContent] = 114	
	<Xml.Serialization.XmlEnum("115")>[SearchOptions] = 115	
	<Xml.Serialization.XmlEnum("116")>[SearchResults] = 116	
	<Xml.Serialization.XmlEnum("117")>[SelfAssessment] = 117	
	<Xml.Serialization.XmlEnum("118")>[SignIn] = 118	
	<Xml.Serialization.XmlEnum("119")>[SignInPopup] = 119	
	<Xml.Serialization.XmlEnum("120")>[SignInShibboleth] = 120	
	<Xml.Serialization.XmlEnum("121")>[SiteMap] = 121	
	<Xml.Serialization.XmlEnum("122")>[Slides] = 122	
	<Xml.Serialization.XmlEnum("125")>[STIndex] = 125	
	<Xml.Serialization.XmlEnum("123")>[StaticPage] = 123	
	<Xml.Serialization.XmlEnum("124")>[Submit] = 124	
	<Xml.Serialization.XmlEnum("126")>[SubmitManuscript] = 126	
	<Xml.Serialization.XmlEnum("127")>[Test] = 127	
	<Xml.Serialization.XmlEnum("128")>[UserProfile] = 128	
	<Xml.Serialization.XmlEnum("129")>[Videos] = 129	
	<Xml.Serialization.XmlEnum("130")>[Volume] = 130	
	<Xml.Serialization.XmlEnum("131")>[WebStateInformation] = 131	
End Enum


	''' <summary>
	''' These are the User Controls for Configuration
	''' </summary>
	''' <remarks></remarks>

Public Enum eConfigUserControls As Integer
	<Xml.Serialization.XmlEnum("11")>[EditorsChoice] = 11	
	<Xml.Serialization.XmlEnum("7")>[FeaturedArticles] = 7	
	<Xml.Serialization.XmlEnum("16")>[FeaturedCME] = 16	
	<Xml.Serialization.XmlEnum("8")>[FirstPagePreview] = 8	
	<Xml.Serialization.XmlEnum("13")>[GetCitation] = 13	
	<Xml.Serialization.XmlEnum("18")>[InstitutionalInheritanceMessaging] = 18	
	<Xml.Serialization.XmlEnum("19")>[InstitutionalLogo] = 19	
	<Xml.Serialization.XmlEnum("14")>[IssueInfoBox] = 14	
	<Xml.Serialization.XmlEnum("6")>[MostReadAndCited] = 6	
	<Xml.Serialization.XmlEnum("12")>[PopUpDataSupplement] = 12	
	<Xml.Serialization.XmlEnum("17")>[RelatedArticleLinks] = 17	
	<Xml.Serialization.XmlEnum("1")>[RelatedArticles] = 1	
	<Xml.Serialization.XmlEnum("4")>[RelatedBooks] = 4	
	<Xml.Serialization.XmlEnum("15")>[RelatedCME] = 15	
	<Xml.Serialization.XmlEnum("3")>[RelatedPubMed] = 3	
	<Xml.Serialization.XmlEnum("2")>[RelatedTopics] = 2	
	<Xml.Serialization.XmlEnum("9")>[SendEmail] = 9	
	<Xml.Serialization.XmlEnum("20")>[TableOfContents] = 20	
	<Xml.Serialization.XmlEnum("21")>[TableOfContentsMobile] = 21	
	<Xml.Serialization.XmlEnum("5")>[Toolbox] = 5	
	<Xml.Serialization.XmlEnum("10")>[UserAlerts] = 10	
End Enum


	''' <summary>
	''' These are the Configuration Value Types 
	''' </summary>
	''' <remarks></remarks>

Public Enum eConfigValueTypes As Integer
	<Xml.Serialization.XmlEnum("1")>[Integer] = 1	
	<Xml.Serialization.XmlEnum("2")>[String] = 2	
	<Xml.Serialization.XmlEnum("3")>[Boolean] = 3	
	<Xml.Serialization.XmlEnum("4")>[Decimal] = 4	
	<Xml.Serialization.XmlEnum("5")>[Citation] = 5	
	<Xml.Serialization.XmlEnum("6")>[DateTime] = 6	
End Enum


	''' <summary>
	''' These are the Configurable Settings Defaults
	''' </summary>
	''' <remarks></remarks>

Public Enum eConfigSettings As Integer
	<Xml.Serialization.XmlEnum("1")>[UserAgent] = 1	
	<Xml.Serialization.XmlEnum("2")>[OpenUrlDefaultImagePath] = 2	
	<Xml.Serialization.XmlEnum("3")>[InstitutionalLogoPath] = 3	
	<Xml.Serialization.XmlEnum("4")>[SponsorLogoPath] = 4	
	<Xml.Serialization.XmlEnum("5")>[ShortCopyrightText] = 5	
	<Xml.Serialization.XmlEnum("6")>[TechnicalSupportEmailAddress] = 6	
	<Xml.Serialization.XmlEnum("7")>[SiteUrl] = 7	
	<Xml.Serialization.XmlEnum("8")>[RightsLinkUrlBase] = 8	
	<Xml.Serialization.XmlEnum("11")>[ClientUsageViolationThreshold] = 11	
	<Xml.Serialization.XmlEnum("12")>[AbusePolicyShutdownNotificationSubjectText] = 12	
	<Xml.Serialization.XmlEnum("13")>[AbusePolicyShutdownNotificationText] = 13	
	<Xml.Serialization.XmlEnum("20")>[PublisherEmailForAbuseMonitoring] = 20	
	<Xml.Serialization.XmlEnum("21")>[SilverchairEmailForAbuseMonitoring] = 21	
	<Xml.Serialization.XmlEnum("22")>[EnableAbuseMonitering] = 22	
	<Xml.Serialization.XmlEnum("28")>[EnvironmentID] = 28	
	<Xml.Serialization.XmlEnum("39")>[IncludePrismTagsInRSSFeeds] = 39	
	<Xml.Serialization.XmlEnum("42")>[DefaultErrorPageDisplayMessage] = 42	
	<Xml.Serialization.XmlEnum("43")>[AbstractViewDisplayTextForAbuseMonitoring] = 43	
	<Xml.Serialization.XmlEnum("44")>[EmailFromForAbuseMonitoring] = 44	
	<Xml.Serialization.XmlEnum("45")>[ShutdownNotificationCCListForAbuseMonitoring] = 45	
	<Xml.Serialization.XmlEnum("46")>[ShutSiteDownForAbuseMonitoring] = 46	
	<Xml.Serialization.XmlEnum("48")>[PublisherNameForAbuseMonitoring] = 48	
	<Xml.Serialization.XmlEnum("49")>[EnableNewAuthentication] = 49	
	<Xml.Serialization.XmlEnum("50")>[PerformAccessCheckForCorridor] = 50	
	<Xml.Serialization.XmlEnum("51")>[SiteMapIncludeBookContentForCrawling] = 51	
	<Xml.Serialization.XmlEnum("52")>[SiteMapExcludeNonBookCollections] = 52	
	<Xml.Serialization.XmlEnum("53")>[SiteMapSectionTypeIDListIncludedForBookContent] = 53	
	<Xml.Serialization.XmlEnum("55")>[WebServicePingRequestCacheTimeout] = 55	
	<Xml.Serialization.XmlEnum("58")>[TimeoutErrorMessage] = 58	
	<Xml.Serialization.XmlEnum("59")>[EnableInstitutionalSubscriptionInheritance] = 59	
	<Xml.Serialization.XmlEnum("60")>[InstitutionalSubscriptionInheritanceTimeOut] = 60	
	<Xml.Serialization.XmlEnum("61")>[PasswordResetNonMatch] = 61	
	<Xml.Serialization.XmlEnum("62")>[PasswordResetNoEmailAddress] = 62	
	<Xml.Serialization.XmlEnum("63")>[PasswordResetEmailAddressRegexPattern] = 63	
	<Xml.Serialization.XmlEnum("64")>[PasswordResetEmailFrom] = 64	
	<Xml.Serialization.XmlEnum("65")>[PasswordResetEmailSubject] = 65	
	<Xml.Serialization.XmlEnum("66")>[PasswordResetEmailBody] = 66	
	<Xml.Serialization.XmlEnum("67")>[PasswordResetEmailSignature] = 67	
	<Xml.Serialization.XmlEnum("68")>[PasswordResetSuccessFeedback] = 68	
	<Xml.Serialization.XmlEnum("69")>[PasswordResetLabelTitle] = 69	
	<Xml.Serialization.XmlEnum("70")>[PasswordResetLabelInstructions] = 70	
	<Xml.Serialization.XmlEnum("71")>[PasswordResetLabelUsernameField] = 71	
	<Xml.Serialization.XmlEnum("72")>[PasswordResetLabelEmailField] = 72	
	<Xml.Serialization.XmlEnum("73")>[PasswordResetValidatorErrorMessage] = 73	
	<Xml.Serialization.XmlEnum("74")>[PasswordResetValidatorInstructions] = 74	
	<Xml.Serialization.XmlEnum("75")>[PasswordResetFieldValidatorCustomErrorMessage] = 75	
	<Xml.Serialization.XmlEnum("76")>[UseRedesignedPsychNews] = 76	
	<Xml.Serialization.XmlEnum("77")>[EnablePsychNewsAlertBlogIntegrationWidget] = 77	
	<Xml.Serialization.XmlEnum("78")>[FirstPagePreviewReferredFromGoogle] = 78	
	<Xml.Serialization.XmlEnum("79")>[FirstPagePreviewRedirectSite] = 79	
	<Xml.Serialization.XmlEnum("80")>[UseRedesignedDSMV] = 80	
	<Xml.Serialization.XmlEnum("81")>[EnableIssueDateAccess] = 81	
	<Xml.Serialization.XmlEnum("85")>[ShowUmbrellaSignIn] = 85	
	<Xml.Serialization.XmlEnum("86")>[SolrIsEnabledForInjestor] = 86	
	<Xml.Serialization.XmlEnum("88")>[SolrIsChapterDocument] = 88	
	<Xml.Serialization.XmlEnum("89")>[UseNLMHeadings] = 89	
	<Xml.Serialization.XmlEnum("90")>[UseRedesignedCCWW] = 90	
	<Xml.Serialization.XmlEnum("91")>[SolrIsEnabledOnFrontEnd] = 91	
	<Xml.Serialization.XmlEnum("93")>[CustomClientFlag1] = 93	
	<Xml.Serialization.XmlEnum("94")>[EnableDisappearingProductReleaseValve] = 94	
	<Xml.Serialization.XmlEnum("95")>[SolrJournalAttributeToDisplayInCitationSection] = 95	
	<Xml.Serialization.XmlEnum("97")>[DataDumpEnabled] = 97	
	<Xml.Serialization.XmlEnum("98")>[DataDumpProcedureNameFilter] = 98	
	<Xml.Serialization.XmlEnum("99")>[BasicSearchFieldLimit] = 99	
	<Xml.Serialization.XmlEnum("105")>[EnablePOLCompanion] = 105	
	<Xml.Serialization.XmlEnum("106")>[SiteMapIncludeVideoContentForCrawling] = 106	
	<Xml.Serialization.XmlEnum("107")>[SolrInjestorDSMBookList] = 107	
	<Xml.Serialization.XmlEnum("118")>[EnableTocHeadingModel] = 118	
	<Xml.Serialization.XmlEnum("119")>[RemoveAP] = 119	
	<Xml.Serialization.XmlEnum("120")>[HideJMIMarketingSelfServe] = 120	
	<Xml.Serialization.XmlEnum("121")>[HideJATISMarketingSelfServe] = 121	
	<Xml.Serialization.XmlEnum("122")>[SolrBookCoverImageUrl] = 122	
	<Xml.Serialization.XmlEnum("123")>[SolrCutoffBeginDateToIndexArticlePaperNumber] = 123	
	<Xml.Serialization.XmlEnum("124")>[SolrIndexBookExcerptField] = 124	
	<Xml.Serialization.XmlEnum("125")>[SolrIsEnabledForSearchAlerts] = 125	
	<Xml.Serialization.XmlEnum("126")>[SolrAutoSuggestMinimumCharactersLength] = 126	
	<Xml.Serialization.XmlEnum("127")>[WoSCitationArticleCutoffStartDate] = 127	
	<Xml.Serialization.XmlEnum("128")>[SolrIngestorBatchSize] = 128	
	<Xml.Serialization.XmlEnum("129")>[AutoLoginUsingIndividualCookie] = 129	
	<Xml.Serialization.XmlEnum("130")>[EnableInstitutionalTokens] = 130	
	<Xml.Serialization.XmlEnum("131")>[HideNEUROWMarketingSelfServe] = 131	
	<Xml.Serialization.XmlEnum("132")>[UseUmbrellaSiteIdForSearchAlerts] = 132	
	<Xml.Serialization.XmlEnum("133")>[SentEmailConfirmationText] = 133	
	<Xml.Serialization.XmlEnum("134")>[UseShortTitleWidgetMostRead] = 134	
	<Xml.Serialization.XmlEnum("135")>[UseShortTitleWidgetRelatedArticle] = 135	
	<Xml.Serialization.XmlEnum("136")>[UseInstitutionalLogoHyperlink] = 136	
	<Xml.Serialization.XmlEnum("138")>[UMLSSources] = 138	
	<Xml.Serialization.XmlEnum("139")>[HideRiskMarketingSelfServe] = 139	
	<Xml.Serialization.XmlEnum("140")>[PdfConverterLicenseKey] = 140	
	<Xml.Serialization.XmlEnum("141")>[EnableFullSitePreview] = 141	
	<Xml.Serialization.XmlEnum("142")>[EnableGoogleFreeArticleMetaTag] = 142	
	<Xml.Serialization.XmlEnum("143")>[ContactUsEmailAddress] = 143	
	<Xml.Serialization.XmlEnum("144")>[ContactUsBccEmailAddresses] = 144	
	<Xml.Serialization.XmlEnum("146")>[SiteMapIncludeGbosContentForCrawling] = 146	
	<Xml.Serialization.XmlEnum("147")>[SiteMapIncludeSEOFriendlyUrlsForGbosContent] = 147	
	<Xml.Serialization.XmlEnum("149")>[SiteMapExcludeGbosContainerIDsList] = 149	
	<Xml.Serialization.XmlEnum("150")>[SiteMapIncludeBrowsePagesForGbosContent] = 150	
	<Xml.Serialization.XmlEnum("151")>[SiteMapExcludeGbosContainerIDsListForBrowsePages] = 151	
	<Xml.Serialization.XmlEnum("152")>[EnableArticleDateSet] = 152	
	<Xml.Serialization.XmlEnum("153")>[SetCitationOnlineDatetag] = 153	
	<Xml.Serialization.XmlEnum("154")>[UseCanonicalUrl] = 154	
	<Xml.Serialization.XmlEnum("155")>[JACC_DomainNameSwitch] = 155	
	<Xml.Serialization.XmlEnum("156")>[CommentAlertEmailFromText] = 156	
	<Xml.Serialization.XmlEnum("157")>[CommentAlertEmailSubjectText] = 157	
	<Xml.Serialization.XmlEnum("158")>[CommentAlertEmailBodyText] = 158	
	<Xml.Serialization.XmlEnum("159")>[IncludeFullTextWorldReadableGoogleMetaTag] = 159	
	<Xml.Serialization.XmlEnum("161")>[AddContainsPodcastFlagOnTocPage] = 161	
	<Xml.Serialization.XmlEnum("162")>[RequireSignInToAccessFreePDF] = 162	
	<Xml.Serialization.XmlEnum("163")>[SiteMapIncludeMultimediaContentForCrawling] = 163	
	<Xml.Serialization.XmlEnum("164")>[SiteMapMultimediaGroupsForClient] = 164	
	<Xml.Serialization.XmlEnum("168")>[UsePodcastVsMultiMediaPlayerForPreview] = 168	
	<Xml.Serialization.XmlEnum("169")>[SiteMapIncludeMobileContentForCrawling] = 169	
	<Xml.Serialization.XmlEnum("173")>[ArticleClientTypeIdsForInvitedCommentaryEditorial] = 173	
	<Xml.Serialization.XmlEnum("177")>[Show_JACC_EP_Journal] = 177	
	<Xml.Serialization.XmlEnum("179")>[HideMicroSiteProducts] = 179	
	<Xml.Serialization.XmlEnum("180")>[HideMicroSiteIds] = 180	
	<Xml.Serialization.XmlEnum("181")>[EnableFreeCmeTokens] = 181	
	<Xml.Serialization.XmlEnum("182")>[FreeCmeTokenProductId] = 182	
	<Xml.Serialization.XmlEnum("183")>[WoSUseDOIAsDefaultOptionToGetCitations] = 183	
	<Xml.Serialization.XmlEnum("186")>[ShowOnlyRecentContentInMostCited] = 186	
	<Xml.Serialization.XmlEnum("187")>[DisplayCiteCountInMostCitedMostViewedWidget] = 187	
	<Xml.Serialization.XmlEnum("188")>[DisplayViewCountInMostCitedMostViewedWidget] = 188	
	<Xml.Serialization.XmlEnum("189")>[NumPastYearsMostCitedLimitedTo] = 189	
	<Xml.Serialization.XmlEnum("190")>[DisplayRssFeedLinksInMostCitedMostViewedWidget] = 190	
	<Xml.Serialization.XmlEnum("191")>[WoSUseISSNWithJournalTitleToGetCitations] = 191	
	<Xml.Serialization.XmlEnum("192")>[ShowCMEResourceCenter] = 192	
	<Xml.Serialization.XmlEnum("193")>[CMEResourceGoLiveDate] = 193	
	<Xml.Serialization.XmlEnum("194")>[SCMDiagnosticsSupportInternalEmailRecipients] = 194	
	<Xml.Serialization.XmlEnum("195")>[SCMDiagnosticsSupportExternalEmailRecipients] = 195	
	<Xml.Serialization.XmlEnum("196")>[EnableRssImporterPodcastDeleteFunctionality] = 196	
	<Xml.Serialization.XmlEnum("197")>[TrackAllConcurrencySeatings] = 197	
	<Xml.Serialization.XmlEnum("198")>[TrustXForwardedFor] = 198	
	<Xml.Serialization.XmlEnum("199")>[LoginPostUrl] = 199	
	<Xml.Serialization.XmlEnum("200")>[LoginSuccessKey] = 200	
	<Xml.Serialization.XmlEnum("201")>[ProcessImages] = 201	
	<Xml.Serialization.XmlEnum("202")>[IncludeAdditionalFields] = 202	
	<Xml.Serialization.XmlEnum("203")>[EnableImpersonation] = 203	
	<Xml.Serialization.XmlEnum("204")>[TwitterArticleTitleLength] = 204	
	<Xml.Serialization.XmlEnum("205")>[TwitterHandle] = 205	
	<Xml.Serialization.XmlEnum("206")>[DruglinkingCoreTimeOut] = 206	
	<Xml.Serialization.XmlEnum("220")>[AllowInstAnonSendEmail] = 220	
	<Xml.Serialization.XmlEnum("221")>[UseAffiliatedInstitutions] = 221	
	<Xml.Serialization.XmlEnum("231")>[ActivateSSO] = 231	
	<Xml.Serialization.XmlEnum("237")>[SolrExcludeSiteIDs] = 237	
	<Xml.Serialization.XmlEnum("239")>[SolrTaxonomyDataImportHandlerEnabled] = 239	
	<Xml.Serialization.XmlEnum("240")>[CommentAuthorAlertEmailBodyText] = 240	
	<Xml.Serialization.XmlEnum("241")>[CommentAuthorAlertEmailSubjectText] = 241	
	<Xml.Serialization.XmlEnum("242")>[CommentAuthorAlertEmailBodyTextForRejected] = 242	
	<Xml.Serialization.XmlEnum("243")>[AuthorMetaTagCitationFormat] = 243	
	<Xml.Serialization.XmlEnum("301")>[IncludeAbstractGoogleMetaTag] = 301	
	<Xml.Serialization.XmlEnum("304")>[DynamicSelfServeBoxesList] = 304	
	<Xml.Serialization.XmlEnum("305")>[PowerPointImageScaleFactor] = 305	
	<Xml.Serialization.XmlEnum("306")>[PowerPointImageLeftPositionFactor] = 306	
	<Xml.Serialization.XmlEnum("307")>[PowerPointImageTopPositionFactor] = 307	
	<Xml.Serialization.XmlEnum("308")>[ArticleAccessTypeIdsForCopyrightSuppression] = 308	
	<Xml.Serialization.XmlEnum("309")>[DefaultCopyrightStatementTemplateForEmptyCopyright] = 309	
	<Xml.Serialization.XmlEnum("311")>[ExtractFiguresFromAllSections] = 311	
	<Xml.Serialization.XmlEnum("313")>[AdobeTagManagerHeadScriptUrl] = 313	
	<Xml.Serialization.XmlEnum("315")>[IncludeArticleUpdateInfoInArticleAlertEmail] = 315	
End Enum


	''' <summary>
	''' These are the contentResolverTypes
	''' </summary>
	''' <remarks></remarks>

Public Enum eContentResolverTypes As Integer
	<Xml.Serialization.XmlEnum("1")>[PMID] = 1	
	<Xml.Serialization.XmlEnum("2")>[DOI] = 2	
	<Xml.Serialization.XmlEnum("3")>[LegacyID] = 3	
	<Xml.Serialization.XmlEnum("4")>[aID] = 4	
End Enum


	''' <summary>
	''' These are the contentResolverTypes
	''' </summary>
	''' <remarks></remarks>

Public Enum eScheduleTypes As Integer
	<Xml.Serialization.XmlEnum("1")>[Daily] = 1	
	<Xml.Serialization.XmlEnum("2")>[Weekly] = 2	
	<Xml.Serialization.XmlEnum("3")>[Monthly] = 3	
	<Xml.Serialization.XmlEnum("4")>[Custom] = 4	
	<Xml.Serialization.XmlEnum("5")>[BiWeekly] = 5	
	<Xml.Serialization.XmlEnum("6")>[BiMonthly] = 6	
	<Xml.Serialization.XmlEnum("7")>[TwiceMonthly] = 7	
	<Xml.Serialization.XmlEnum("8")>[Hourly] = 8	
End Enum


	''' <summary>
	''' These are the Configurable Settings Defaults for SiteMaster
	''' </summary>
	''' <remarks>eConfigSettings is for front-end/content sites only</remarks>

Public Enum eConfigSettingsSiteMaster As Integer
	<Xml.Serialization.XmlEnum("9")>[SM_AdminDashboardNotificationText] = 9	
	<Xml.Serialization.XmlEnum("14")>[AbusePolicyReinstatementRequestSubjectText] = 14	
	<Xml.Serialization.XmlEnum("15")>[AbusePolicyReinstatementRequestText] = 15	
	<Xml.Serialization.XmlEnum("16")>[AbusePolicyReinstatementRequestApprovalSubjectText] = 16	
	<Xml.Serialization.XmlEnum("17")>[AbusePolicyReinstatementRequestApprovalText] = 17	
	<Xml.Serialization.XmlEnum("18")>[SiteMasterCounterReportsLegacy] = 18	
	<Xml.Serialization.XmlEnum("26")>[SushiInstitutionalAccessEmail] = 26	
	<Xml.Serialization.XmlEnum("27")>[SushiPublisherAccessEmail] = 27	
	<Xml.Serialization.XmlEnum("29")>[SushiInstitutionalAccessEmailBody] = 29	
	<Xml.Serialization.XmlEnum("30")>[SushiPublisherAccessEmailBody] = 30	
	<Xml.Serialization.XmlEnum("31")>[SushiInstitutionalAccessEmailSubject] = 31	
	<Xml.Serialization.XmlEnum("32")>[SushiPublisherAccessEmailSubject] = 32	
	<Xml.Serialization.XmlEnum("33")>[SushiInstitutionalAccessEmailFromAddr] = 33	
	<Xml.Serialization.XmlEnum("34")>[SushiPublisherAccessEmailFromAddr] = 34	
	<Xml.Serialization.XmlEnum("40")>[SiteMasterRestatementMsg] = 40	
	<Xml.Serialization.XmlEnum("54")>[MediaSharePath] = 54	
	<Xml.Serialization.XmlEnum("56")>[SM_AllowInstitutionalAdminsToEditShibbolethInfo] = 56	
	<Xml.Serialization.XmlEnum("57")>[SM_EnableShibboleth] = 57	
	<Xml.Serialization.XmlEnum("82")>[SiteMasterGoogleAnalyticsScript] = 82	
	<Xml.Serialization.XmlEnum("83")>[SiteMasterGoogleAnalyticsAccount] = 83	
	<Xml.Serialization.XmlEnum("84")>[SiteMasterGoogleAnalyticsDomainName] = 84	
	<Xml.Serialization.XmlEnum("92")>[EnableEditInstitutionalAdminMasterInfo] = 92	
	<Xml.Serialization.XmlEnum("101")>[AutomatedTollFreeLinksByEmailEnabled] = 101	
	<Xml.Serialization.XmlEnum("102")>[EnableTollFreeLinks] = 102	
	<Xml.Serialization.XmlEnum("103")>[DefaultTollFreeLinksDescription] = 103	
	<Xml.Serialization.XmlEnum("104")>[DefaultTollFreeLinksExpiration] = 104	
	<Xml.Serialization.XmlEnum("108")>[EnableEditInstitutionLogo] = 108	
	<Xml.Serialization.XmlEnum("109")>[EnableEditInstitutionLogoForAdmin] = 109	
	<Xml.Serialization.XmlEnum("148")>[SM_RedirectUrlForInsitutionalAdminLogout] = 148	
	<Xml.Serialization.XmlEnum("160")>[ShowCommentAdministrator] = 160	
	<Xml.Serialization.XmlEnum("172")>[ShowTopicCollectionsEditor] = 172	
	<Xml.Serialization.XmlEnum("219")>[SM_AdminDashboardNotificationText_ES] = 219	
	<Xml.Serialization.XmlEnum("224")>[APSDateFormat] = 224	
	<Xml.Serialization.XmlEnum("226")>[BuildManualTokenReplacement] = 226	
	<Xml.Serialization.XmlEnum("227")>[MaximumCharacterCount] = 227	
	<Xml.Serialization.XmlEnum("228")>[BaseTokenVariable] = 228	
	<Xml.Serialization.XmlEnum("229")>[NumberOfTotalTokensInTemplate] = 229	
	<Xml.Serialization.XmlEnum("232")>[UseListOfEmails] = 232	
	<Xml.Serialization.XmlEnum("233")>[CampaignerTestEmailList] = 233	
	<Xml.Serialization.XmlEnum("234")>[InstitutionalAdminCanEditInstitutionalData] = 234	
	<Xml.Serialization.XmlEnum("235")>[APSContactsBatchSize] = 235	
	<Xml.Serialization.XmlEnum("294")>[AllowCreateAccount] = 294	
	<Xml.Serialization.XmlEnum("295")>[HidePrintForInstAnon] = 295	
	<Xml.Serialization.XmlEnum("296")>[AddLinkToEmail] = 296	
	<Xml.Serialization.XmlEnum("297")>[ShowCommentJournals] = 297	
	<Xml.Serialization.XmlEnum("298")>[UseGPTAds] = 298	
	<Xml.Serialization.XmlEnum("299")>[DefaultSpecialtyCategory] = 299	
	<Xml.Serialization.XmlEnum("310")>[InstitutionVendorIdSearchWithin] = 310	
	<Xml.Serialization.XmlEnum("312")>[ShowSpecialOfferManager] = 312	
	<Xml.Serialization.XmlEnum("314")>[LaunchSite] = 314	
End Enum


	''' <summary>
	''' These are the Configurable Setting Types (Public and SiteMaster)
	''' </summary>
	''' <remarks>Type used to differentiate settings between Front-end (Public) and SiteMaster sites</remarks>

Public Enum eConfigSettingTypes As Integer
	<Xml.Serialization.XmlEnum("1")>[Public] = 1	
	<Xml.Serialization.XmlEnum("3")>[SCMAPIs] = 3	
	<Xml.Serialization.XmlEnum("2")>[SiteMaster] = 2	
	<Xml.Serialization.XmlEnum("4")>[Zipline] = 4	
End Enum



	''' <summary>
	''' These are the Deposit Book Types
	''' </summary>
	''' <remarks></remarks>

Public Enum eDepositBookTypes As Integer
	<Xml.Serialization.XmlEnum("1")>[EditedBook] = 1	
	<Xml.Serialization.XmlEnum("2")>[Monograph] = 2	
	<Xml.Serialization.XmlEnum("3")>[Other] = 3	
	<Xml.Serialization.XmlEnum("4")>[Reference] = 4	
End Enum


	''' <summary>
	''' These are the Site Menu Types
	''' </summary>
	''' <remarks></remarks>

Public Enum eSiteMenuTypes As Integer
	<Xml.Serialization.XmlEnum("1")>[Footer] = 1	
	<Xml.Serialization.XmlEnum("2")>[Header] = 2	
	<Xml.Serialization.XmlEnum("3")>[HeaderPreview] = 3	
	<Xml.Serialization.XmlEnum("4")>[FooterPreview] = 4	
	<Xml.Serialization.XmlEnum("5")>[HeaderTaxonomy] = 5	
End Enum


	''' <summary>
	''' These are the LinkDecorations for SiteMenu records to determine how links should be generated
	''' </summary>
	''' <remarks></remarks>
    <Flags>
    Public Enum eLinkDecorations As Integer
        None = 0
        RelNoFollow = 1
    End Enum


	''' <summary>
	''' These are resourceAccessTypes
	''' </summary>
	''' <remarks></remarks>

Public Enum eResourceAccessTypes as Integer
	<Xml.Serialization.XmlEnum("1")>[Private] =1
	<Xml.Serialization.XmlEnum("2")>[FreeView] =2
	<Xml.Serialization.XmlEnum("3")>[OpenAccess] =3
	<Xml.Serialization.XmlEnum("4")>[OpenAccessCCBY] =4
	<Xml.Serialization.XmlEnum("5")>[OpenAccessCCBYND] =5
	<Xml.Serialization.XmlEnum("6")>[OpenAccessCCBYNCSA] =6
	<Xml.Serialization.XmlEnum("7")>[OpenAccessCCBYSA] =7
	<Xml.Serialization.XmlEnum("8")>[OpenAccessCCBYNC] =8
	<Xml.Serialization.XmlEnum("9")>[PrivateOverwrite] =9
	<Xml.Serialization.XmlEnum("10")>[OpenAccessCCBYNCND] =10
	<Xml.Serialization.XmlEnum("11")>[Restricted] =11
	<Xml.Serialization.XmlEnum("12")>[CrownCopyright] =12
	<Xml.Serialization.XmlEnum("13")>[USGov] =13
End Enum


	''' <summary>
	''' These are eConfigSiteSettings
	''' </summary>
	''' <remarks></remarks>
Public Enum eConfigSiteSettings as Integer
	<Xml.Serialization.XmlEnum("35")>[CitationFormat] =35
	<Xml.Serialization.XmlEnum("36")>[CitationFormatShort] =36
	<Xml.Serialization.XmlEnum("37")>[CitationMaxAuthorLimit] =37
	<Xml.Serialization.XmlEnum("38")>[CitationNumberAuthorToShow] =38
	<Xml.Serialization.XmlEnum("137")>[PAPCitationFormat] =137
	<Xml.Serialization.XmlEnum("170")>[DrugLinksDisplay] =170
	<Xml.Serialization.XmlEnum("171")>[HideTopicCollectionIDs] =171
	<Xml.Serialization.XmlEnum("174")>[EmailSiteLevelConfirmation] =174
	<Xml.Serialization.XmlEnum("175")>[EmailBodyTemplate] =175
	<Xml.Serialization.XmlEnum("176")>[EmailCopyrightTemplate] =176
	<Xml.Serialization.XmlEnum("185")>[DrugLinkDestinationSite] =185
	<Xml.Serialization.XmlEnum("225")>[AutoLoginUrlReferIPAddress] =225
	<Xml.Serialization.XmlEnum("236")>[InlineMultimediaBookList] =236
	<Xml.Serialization.XmlEnum("238")>[SolrExcludeGroupNames] =238
	<Xml.Serialization.XmlEnum("300")>[GbosUpdateCitationFormat] =300
	<Xml.Serialization.XmlEnum("302")>[ShareContentLinkMaxUsages] =302
	<Xml.Serialization.XmlEnum("303")>[ShareContentLinkTTLHours] =303
End Enum


	''' <summary>
	''' These are eConfigJournalSettings
	''' </summary>
	''' <remarks></remarks>
Public Enum eConfigJournalSettings as Integer
	<Xml.Serialization.XmlEnum("19")>[BlockCrawlerBeforeDate] =19
	<Xml.Serialization.XmlEnum("23")>[BlockCrawlerForJournalID] =23
	<Xml.Serialization.XmlEnum("24")>[ThisWeekArticleType] =24
	<Xml.Serialization.XmlEnum("25")>[AboutTheCoverArticleType] =25
	<Xml.Serialization.XmlEnum("41")>[BlockCrawlerForArticleClientTypes] =41
End Enum


	''' <summary>
	''' These are eCitationReplacementStrings
	''' </summary>
	''' <remarks></remarks>
Public Enum eCitationReplacementStrings as Integer
	<Xml.Serialization.XmlEnum("9")>[Abstract] =9
	<Xml.Serialization.XmlEnum("24")>[AccessedDate] =24
	<Xml.Serialization.XmlEnum("1")>[Author] =1
	<Xml.Serialization.XmlEnum("23")>[BookCitationName] =23
	<Xml.Serialization.XmlEnum("11")>[DOI] =11
	<Xml.Serialization.XmlEnum("22")>[Editor] =22
	<Xml.Serialization.XmlEnum("6")>[EndPage] =6
	<Xml.Serialization.XmlEnum("20")>[EntryType] =20
	<Xml.Serialization.XmlEnum("19")>[ePrint] =19
	<Xml.Serialization.XmlEnum("10")>[ISBN] =10
	<Xml.Serialization.XmlEnum("4")>[JournalName] =4
	<Xml.Serialization.XmlEnum("14")>[JournalNameAbbreviation] =14
	<Xml.Serialization.XmlEnum("3")>[Notes] =3
	<Xml.Serialization.XmlEnum("8")>[Number] =8
	<Xml.Serialization.XmlEnum("21")>[Pages] =21
	<Xml.Serialization.XmlEnum("16")>[PublicationDay] =16
	<Xml.Serialization.XmlEnum("17")>[PublicationMonth] =17
	<Xml.Serialization.XmlEnum("13")>[PublicationType] =13
	<Xml.Serialization.XmlEnum("18")>[PublicationYear] =18
	<Xml.Serialization.XmlEnum("25")>[SiteName] =25
	<Xml.Serialization.XmlEnum("15")>[Source] =15
	<Xml.Serialization.XmlEnum("5")>[StartPage] =5
	<Xml.Serialization.XmlEnum("2")>[Title] =2
	<Xml.Serialization.XmlEnum("12")>[Url] =12
	<Xml.Serialization.XmlEnum("7")>[Volume] =7
End Enum



	''' <summary>
	''' 
	''' </summary>
	''' <remarks></remarks>
Public Enum eEnvironments as Integer
	<Xml.Serialization.XmlEnum("1")>[Dev] =1
	<Xml.Serialization.XmlEnum("2")>[QA] =2
	<Xml.Serialization.XmlEnum("3")>[Staging] =3
	<Xml.Serialization.XmlEnum("4")>[Production] =4
End Enum



	''' <summary>
	''' These are UserRoles
	''' </summary>
	''' <remarks></remarks>
Public Enum eUserRole as Integer
	<Xml.Serialization.XmlEnum("352")>[AccountsReportsAdministrator] =352
	<Xml.Serialization.XmlEnum("6")>[CMEUser] =6
	<Xml.Serialization.XmlEnum("358")>[CommentAdministrator] =358
	<Xml.Serialization.XmlEnum("351")>[ContentAdministrator] =351
	<Xml.Serialization.XmlEnum("30")>[ContentLoader] =30
	<Xml.Serialization.XmlEnum("13")>[ContentPreviewer] =13
	<Xml.Serialization.XmlEnum("9")>[ContentProductionManager] =9
	<Xml.Serialization.XmlEnum("354")>[CurriculumAdministrator] =354
	<Xml.Serialization.XmlEnum("361")>[EditArticleClientTypesUser] =361
	<Xml.Serialization.XmlEnum("5")>[IndividualUser] =5
	<Xml.Serialization.XmlEnum("4")>[InstitutionalAdministrator] =4
	<Xml.Serialization.XmlEnum("2")>[InstitutionalAnonymous] =2
	<Xml.Serialization.XmlEnum("360")>[InstitutionalCOUNTERReports] =360
	<Xml.Serialization.XmlEnum("3")>[InstitutionalSubUser] =3
	<Xml.Serialization.XmlEnum("355")>[Instructor] =355
	<Xml.Serialization.XmlEnum("357")>[InstructorGuide] =357
	<Xml.Serialization.XmlEnum("356")>[Learner] =356
	<Xml.Serialization.XmlEnum("1")>[NonAuthenticatedUser] =1
	<Xml.Serialization.XmlEnum("359")>[PassiveCMEEligible] =359
	<Xml.Serialization.XmlEnum("368")>[ProductBuilderAdmin] =368
	<Xml.Serialization.XmlEnum("369")>[ProductBuilderReadOnly] =369
	<Xml.Serialization.XmlEnum("12")>[ReportingManager] =12
	<Xml.Serialization.XmlEnum("8")>[SiteAdministrator] =8
	<Xml.Serialization.XmlEnum("365")>[SiteBuilderUIAdmin] =365
	<Xml.Serialization.XmlEnum("364")>[SiteBuilderUIReadOnly] =364
	<Xml.Serialization.XmlEnum("367")>[SiteBuilderViewLiveLimitedSites] =367
	<Xml.Serialization.XmlEnum("366")>[SiteBuilderViewPreviewSites] =366
	<Xml.Serialization.XmlEnum("11")>[SubscriptionManager] =11
	<Xml.Serialization.XmlEnum("7")>[SuperUser] =7
	<Xml.Serialization.XmlEnum("353")>[SushiUser] =353
	<Xml.Serialization.XmlEnum("363")>[TaxonomyManager] =363
	<Xml.Serialization.XmlEnum("370")>[TestAccount] =370
	<Xml.Serialization.XmlEnum("14")>[UnderDevelopmentFeatureUser] =14
End Enum


	''' <summary>
	''' These are Permissions
	''' </summary>
	''' <remarks></remarks>
Public Enum ePermission as Integer
	<Xml.Serialization.XmlEnum("1")>[AccessToArticles] =1
	<Xml.Serialization.XmlEnum("2")>[AccessToOtherContentTypesBehindSecurity] =2
	<Xml.Serialization.XmlEnum("3")>[CME] =3
	<Xml.Serialization.XmlEnum("4")>[CommentOnArticles] =4
	<Xml.Serialization.XmlEnum("5")>[EmailAlerts] =5
	<Xml.Serialization.XmlEnum("6")>[SaveContent] =6
	<Xml.Serialization.XmlEnum("7")>[SeeComments] =7
	<Xml.Serialization.XmlEnum("8")>[UserManagement] =8
	<Xml.Serialization.XmlEnum("9")>[ProductionManagement] =9
	<Xml.Serialization.XmlEnum("10")>[SiteEditingLayout] =10
	<Xml.Serialization.XmlEnum("11")>[Marketing] =11
	<Xml.Serialization.XmlEnum("12")>[SUMO] =12
	<Xml.Serialization.XmlEnum("13")>[StatsMaster] =13
	<Xml.Serialization.XmlEnum("14")>[DataSupplements] =14
	<Xml.Serialization.XmlEnum("15")>[Email] =15
	<Xml.Serialization.XmlEnum("16")>[GetCitation] =16
	<Xml.Serialization.XmlEnum("17")>[PDFDownload] =17
	<Xml.Serialization.XmlEnum("18")>[PrintableView] =18
	<Xml.Serialization.XmlEnum("19")>[ReprintsPermissions] =19
	<Xml.Serialization.XmlEnum("20")>[ShareToSocialNetwork] =20
	<Xml.Serialization.XmlEnum("21")>[SubmitComment] =21
	<Xml.Serialization.XmlEnum("22")>[SubmitLetter] =22
	<Xml.Serialization.XmlEnum("23")>[VideoSupplements] =23
	<Xml.Serialization.XmlEnum("24")>[InstitutionCounterReport] =24
	<Xml.Serialization.XmlEnum("25")>[ViewUnpublishedContent] =25
	<Xml.Serialization.XmlEnum("26")>[ViewFeaturesUnderDevelopment] =26
	<Xml.Serialization.XmlEnum("27")>[Slideset] =27
	<Xml.Serialization.XmlEnum("28")>[PublisherSushiReports] =28
	<Xml.Serialization.XmlEnum("29")>[InstitutionalSushiReports] =29
	<Xml.Serialization.XmlEnum("30")>[ActivateorDeactivateSOLforanInstitution] =30
	<Xml.Serialization.XmlEnum("31")>[ApplyorRemoveSOLInstructorDesignation] =31
	<Xml.Serialization.XmlEnum("32")>[CreateCurriculaandCourses] =32
	<Xml.Serialization.XmlEnum("33")>[AssignCoursetoLearners] =33
	<Xml.Serialization.XmlEnum("34")>[ManageGroupofLearners] =34
	<Xml.Serialization.XmlEnum("35")>[ReviewLearnersAnswers] =35
	<Xml.Serialization.XmlEnum("36")>[RunReportsOnLearnersCompletionProgress] =36
	<Xml.Serialization.XmlEnum("37")>[DesignateUserAsInstructor] =37
	<Xml.Serialization.XmlEnum("38")>[CompleteCourse] =38
	<Xml.Serialization.XmlEnum("39")>[CanViewInstructorGuides] =39
	<Xml.Serialization.XmlEnum("40")>[AdministrateComment] =40
	<Xml.Serialization.XmlEnum("41")>[PassiveCMEEligible] =41
	<Xml.Serialization.XmlEnum("42")>[PublisherCounterReport] =42
	<Xml.Serialization.XmlEnum("43")>[CanViewCounterReport] =43
	<Xml.Serialization.XmlEnum("44")>[CanEditArticleClientTypesUser] =44
	<Xml.Serialization.XmlEnum("45")>[CanUploadTaxonomy] =45
	<Xml.Serialization.XmlEnum("46")>[SiteBuilderUIReadonly] =46
	<Xml.Serialization.XmlEnum("47")>[SiteBuilderUIAdmin] =47
	<Xml.Serialization.XmlEnum("48")>[SiteBuilderViewPreviewSites] =48
	<Xml.Serialization.XmlEnum("49")>[SiteBuilderViewLiveLimitedSites] =49
	<Xml.Serialization.XmlEnum("50")>[SubmitContent] =50
	<Xml.Serialization.XmlEnum("51")>[DeleteContent] =51
	<Xml.Serialization.XmlEnum("52")>[PublishContent] =52
	<Xml.Serialization.XmlEnum("53")>[UnpublishContent] =53
	<Xml.Serialization.XmlEnum("54")>[ViewUsersSubmissions] =54
	<Xml.Serialization.XmlEnum("55")>[ViewClientsSubmissions] =55
	<Xml.Serialization.XmlEnum("56")>[AdjustQueue] =56
	<Xml.Serialization.XmlEnum("57")>[CanViewTaxonomy] =57
	<Xml.Serialization.XmlEnum("58")>[CanViewContent] =58
	<Xml.Serialization.XmlEnum("59")>[CanGetOrRetrySubmission] =59
	<Xml.Serialization.XmlEnum("60")>[AssignSitesToUserAccounts] =60
	<Xml.Serialization.XmlEnum("61")>[OpenIssue] =61
	<Xml.Serialization.XmlEnum("62")>[CloseIssue] =62
	<Xml.Serialization.XmlEnum("63")>[ProductBuilderReadonly] =63
	<Xml.Serialization.XmlEnum("64")>[ProductBuilderAdmin] =64
	<Xml.Serialization.XmlEnum("65")>[DepositManagement] =65
End Enum


	''' <summary>
	''' These are solActiveStatusLookups
	''' </summary>
	''' <remarks></remarks>
Public Enum eSolActiveStatuses as Integer
	<Xml.Serialization.XmlEnum("1")>[prepublish] =1
	<Xml.Serialization.XmlEnum("2")>[published] =2
	<Xml.Serialization.XmlEnum("3")>[expired] =3
	<Xml.Serialization.XmlEnum("4")>[deleted] =4
End Enum


	''' <summary>
	''' These are solActivityTypeLookups
	''' </summary>
	''' <remarks></remarks>
Public Enum eSolActivityTypes as Integer
	<Xml.Serialization.XmlEnum("1")>[reading] =1
	<Xml.Serialization.XmlEnum("2")>[other] =2
	<Xml.Serialization.XmlEnum("3")>[externallink] =3
	<Xml.Serialization.XmlEnum("4")>[quiz] =4
	<Xml.Serialization.XmlEnum("5")>[fileupload] =5
	<Xml.Serialization.XmlEnum("6")>[prequiz] =6
	<Xml.Serialization.XmlEnum("7")>[postquiz] =7
End Enum


	''' <summary>
	''' These are solContainerTypeLookups
	''' </summary>
	''' <remarks></remarks>
Public Enum eSolContainerTypes as Integer
	<Xml.Serialization.XmlEnum("1")>[activity] =1
	<Xml.Serialization.XmlEnum("2")>[course] =2
	<Xml.Serialization.XmlEnum("3")>[curriculum] =3
	<Xml.Serialization.XmlEnum("4")>[topic] =4
End Enum


	''' <summary>
	''' These are GBOS Types
	''' </summary>
	''' <remarks></remarks>
Public Enum eGbosType as Integer
	<Xml.Serialization.XmlEnum("1")>[Glossary] =1
	<Xml.Serialization.XmlEnum("2")>[DrugMonograph] =2
	<Xml.Serialization.XmlEnum("3")>[PointofCareTopic] =3
	<Xml.Serialization.XmlEnum("4")>[Question] =4
	<Xml.Serialization.XmlEnum("5")>[calculator] =5
	<Xml.Serialization.XmlEnum("6")>[HerbsandSupplements] =6
	<Xml.Serialization.XmlEnum("7")>[PatientEducationHandout] =7
	<Xml.Serialization.XmlEnum("8")>[Cases] =8
	<Xml.Serialization.XmlEnum("9")>[MGHBookUpdate] =9
	<Xml.Serialization.XmlEnum("10")>[DrugHandout] =10
	<Xml.Serialization.XmlEnum("11")>[QuickTest] =11
	<Xml.Serialization.XmlEnum("12")>[Algorithms] =12
	<Xml.Serialization.XmlEnum("14")>[EvidenceBasedMedicine] =14
	<Xml.Serialization.XmlEnum("15")>[Images] =15
	<Xml.Serialization.XmlEnum("16")>[LabTests] =16
	<Xml.Serialization.XmlEnum("17")>[PediatricCharts] =17
	<Xml.Serialization.XmlEnum("18")>[Procedures] =18
	<Xml.Serialization.XmlEnum("19")>[FreeTextQuesions] =19
	<Xml.Serialization.XmlEnum("20")>[BookUpdate] =20
	<Xml.Serialization.XmlEnum("21")>[BookErrata] =21
	<Xml.Serialization.XmlEnum("22")>[Video] =22
	<Xml.Serialization.XmlEnum("23")>[Guidelines] =23
	<Xml.Serialization.XmlEnum("24")>[FrontMatter] =24
	<Xml.Serialization.XmlEnum("25")>[Quiz] =25
	<Xml.Serialization.XmlEnum("26")>[Acronyms] =26
	<Xml.Serialization.XmlEnum("27")>[Diagnosaurus] =27
	<Xml.Serialization.XmlEnum("28")>[Module] =28
	<Xml.Serialization.XmlEnum("29")>[MGHBlog] =29
	<Xml.Serialization.XmlEnum("30")>[SpecialContent] =30
End Enum



	''' <summary>
	''' These are GBOS Types
	''' </summary>
	''' <remarks></remarks>
Public Enum eConfigApiSettings as Integer
	<Xml.Serialization.XmlEnum("47")>[SCMAPIIssueDefaultArticleCount] =47
	<Xml.Serialization.XmlEnum("100")>[SolrIsEnabledForAPIs] =100
	<Xml.Serialization.XmlEnum("178")>[ImageSourceUrl] =178
	<Xml.Serialization.XmlEnum("184")>[AuthorizationPromptCredentials] =184
End Enum
	

	''' <summary>
	''' These are solLearnerGroupTypes Types
	''' </summary>
	''' <remarks></remarks>
Public Enum eSolLearnerGroupTypes as Integer
	<Xml.Serialization.XmlEnum("1")>[instructorcreated] =1
	<Xml.Serialization.XmlEnum("2")>[PGY1] =2
	<Xml.Serialization.XmlEnum("3")>[PGY2] =3
	<Xml.Serialization.XmlEnum("4")>[PGY3] =4
End Enum
	

	''' <summary>
	''' These are solQuizTypes Types
	''' </summary>
	''' <remarks></remarks>
Public Enum eSolQuizTypes as Integer
	<Xml.Serialization.XmlEnum("1")>[SiteContentAutogenerated] =1
	<Xml.Serialization.XmlEnum("2")>[SiteContentChooseQuestions] =2
	<Xml.Serialization.XmlEnum("3")>[SelfAuthored] =3
	<Xml.Serialization.XmlEnum("4")>[Case] =4
	<Xml.Serialization.XmlEnum("5")>[QandA] =5
	<Xml.Serialization.XmlEnum("6")>[QuestionBank] =6
End Enum
	

	''' <summary>
	''' These are solQuestionTypes Types
	''' </summary>
	''' <remarks></remarks>
Public Enum eSolQuestionTypes as Integer
	<Xml.Serialization.XmlEnum("1")>[truefalse] =1
	<Xml.Serialization.XmlEnum("2")>[multiplechoice] =2
	<Xml.Serialization.XmlEnum("3")>[textentry] =3
	<Xml.Serialization.XmlEnum("4")>[fileupload] =4
	<Xml.Serialization.XmlEnum("5")>[matching] =5
	<Xml.Serialization.XmlEnum("6")>[multianswer] =6
	<Xml.Serialization.XmlEnum("7")>[multianswerordered] =7
End Enum

	

	''' <summary>
	''' These are resourceIndex Types
	''' </summary>
	''' <remarks></remarks>
Public Enum eResourceIndexTypes as Short
	<Xml.Serialization.XmlEnum("1")>[DisplayName] =1
	<Xml.Serialization.XmlEnum("2")>[AltTitle] =2
	<Xml.Serialization.XmlEnum("3")>[DrugBrandName] =3
	<Xml.Serialization.XmlEnum("4")>[DrugGenericName] =4
	<Xml.Serialization.XmlEnum("5")>[Agent] =5
	<Xml.Serialization.XmlEnum("6")>[Diagnosis] =6
	<Xml.Serialization.XmlEnum("7")>[DrugClass] =7
	<Xml.Serialization.XmlEnum("8")>[Symptoms] =8
	<Xml.Serialization.XmlEnum("9")>[Topics] =9
	<Xml.Serialization.XmlEnum("10")>[NationalDrugCode] =10
	<Xml.Serialization.XmlEnum("11")>[AuthoringBody] =11
	<Xml.Serialization.XmlEnum("12")>[PolicyKeyword] =12
	<Xml.Serialization.XmlEnum("13")>[BFKeyword] =13
	<Xml.Serialization.XmlEnum("14")>[FormsKeyword] =14
	<Xml.Serialization.XmlEnum("15")>[GlossaryEquivs] =15
	<Xml.Serialization.XmlEnum("16")>[AZKeyword] =16
	<Xml.Serialization.XmlEnum("17")>[DrugInternational] =17
End Enum


	''' <summary>
	''' These are authorNote Types
	''' </summary>
	''' <remarks></remarks>
Public Enum eAuthorNoteTypes as Integer
	<Xml.Serialization.XmlEnum("1")>[Deceased] =1
	<Xml.Serialization.XmlEnum("2")>[Disclosure] =2
	<Xml.Serialization.XmlEnum("3")>[Other] =3
	<Xml.Serialization.XmlEnum("4")>[CrossReference] =4
End Enum


	''' <summary>
	''' These are shibboleth attribute names and ids
	''' </summary>
	''' <remarks></remarks>

Public Enum eShibolethSSOAttributes As Integer
	<Xml.Serialization.XmlEnum("1")>[AFFILIATION] = 1	
	<Xml.Serialization.XmlEnum("2")>[UNSCOPEDAFFILIATION] = 2	
	<Xml.Serialization.XmlEnum("3")>[ENTITLEMENT] = 3	
End Enum

		
	''' <summary>
	''' Methods for logging into the system. Bit Flag type enumeration (meaning a combination of multiple through bitwise ORs is valid)
	''' See Extensions module in this project for methods to make using them easier
	''' </summary>
	''' <remarks></remarks>
	<Flags()> _
	Public Enum eLoginMethodFlag As Integer
			<Xml.Serialization.XmlEnum("0")>[None] = 0	
			<Xml.Serialization.XmlEnum("1")>[UsernamePasswordCookie] = 1	
			<Xml.Serialization.XmlEnum("2")>[IndividualUsernamePassword] = 2	
			<Xml.Serialization.XmlEnum("4")>[InstitutionalUsernamePassword] = 4	
			<Xml.Serialization.XmlEnum("8")>[IpAuthentication] = 8	
			<Xml.Serialization.XmlEnum("16")>[ReferringUrl] = 16	
			<Xml.Serialization.XmlEnum("32")>[Athens] = 32	
			<Xml.Serialization.XmlEnum("64")>[Shibboleth] = 64	
			<Xml.Serialization.XmlEnum("128")>[AffliationBasedInheritence] = 128	
			<Xml.Serialization.XmlEnum("256")>[MobileCookieForInstitutionalAnon] = 256	
			<Xml.Serialization.XmlEnum("512")>[SpecialClientSpecificIndividual] = 512	
			<Xml.Serialization.XmlEnum("1024")>[SpecialClientSpecificInstitutional] = 1024	
			<Xml.Serialization.XmlEnum("2048")>[AuthenticationToken] = 2048	
			<Xml.Serialization.XmlEnum("4096")>[Impersonation] = 4096	
			<Xml.Serialization.XmlEnum("8192")>[GlobalSso] = 8192	
		End Enum
	



	''' <summary>
	''' These are Book Types
	''' </summary>
	''' <remarks></remarks>

Public Enum eBookTocTypes As Integer
	<Xml.Serialization.XmlEnum("1")>[AZTOC] = 1	
	<Xml.Serialization.XmlEnum("2")>[CategoryTOC] = 2	
	<Xml.Serialization.XmlEnum("3")>[AZandCategoryTOC] = 3	
	<Xml.Serialization.XmlEnum("4")>[ContentSpecificTOC] = 4	
	<Xml.Serialization.XmlEnum("5")>[CasesToc] = 5	
	<Xml.Serialization.XmlEnum("6")>[QandAToc] = 6	
End Enum



	''' <summary>
	''' These are targets for polling deposits (e.g., PubMed)
	''' </summary>
	''' <remarks></remarks>

Public Enum eDepositTargets As Integer
	<Xml.Serialization.XmlEnum("1")>[PubMed] = 1	
	<Xml.Serialization.XmlEnum("2")>[CrossRef] = 2	
	<Xml.Serialization.XmlEnum("3")>[ThirdParty] = 3	
End Enum



	''' <summary>
	''' These are targets for polling deposits (e.g., PubMed)
	''' </summary>
	''' <remarks></remarks>

Public Enum eContentDepositAndQueryStatus As Integer
	<Xml.Serialization.XmlEnum("0")>[NULL] = 0	
	<Xml.Serialization.XmlEnum("1")>[NewArticle] = 1	
	<Xml.Serialization.XmlEnum("2")>[NewPAP] = 2	
	<Xml.Serialization.XmlEnum("3")>[UpdateArticle] = 3	
	<Xml.Serialization.XmlEnum("4")>[Pending] = 4	
	<Xml.Serialization.XmlEnum("5")>[Sent] = 5	
	<Xml.Serialization.XmlEnum("6")>[Processing] = 6	
	<Xml.Serialization.XmlEnum("7")>[Complete] = 7	
	<Xml.Serialization.XmlEnum("8")>[Failed] = 8	
	<Xml.Serialization.XmlEnum("9")>[GiveUp] = 9	
	<Xml.Serialization.XmlEnum("10")>[Deleted] = 10	
	<Xml.Serialization.XmlEnum("11")>[Poll] = 11	
End Enum


	''' <summary>
	''' These enums for Solr Facet Display Types.
	''' </summary>
	''' <remarks></remarks>

Public Enum eSolrFacetDisplayTypes As Integer
	<Xml.Serialization.XmlEnum("1")>[Link] = 1	
	<Xml.Serialization.XmlEnum("2")>[CheckBox] = 2	
	<Xml.Serialization.XmlEnum("3")>[Dropdown] = 3	
End Enum


	''' <summary>
	''' These enums for Solr Facet Sort Types.
	''' </summary>
	''' <remarks></remarks>

Public Enum eSolrFacetSortTypes As Integer
	<Xml.Serialization.XmlEnum("1")>[Count] = 1	
	<Xml.Serialization.XmlEnum("2")>[Index] = 2	
End Enum


	''' <summary>
	''' These enums for Solr Facet Types.
	''' </summary>
	''' <remarks></remarks>

Public Enum eSolrFacetTypes As Integer
	<Xml.Serialization.XmlEnum("1")>[SingleSelect] = 1	
	<Xml.Serialization.XmlEnum("2")>[MultiSelect] = 2	
	<Xml.Serialization.XmlEnum("3")>[SinglePrefix] = 3	
	<Xml.Serialization.XmlEnum("4")>[Prefix] = 4	
	<Xml.Serialization.XmlEnum("5")>[Dropdown] = 5	
	<Xml.Serialization.XmlEnum("6")>[Taxonomy] = 6	
End Enum


	''' <summary>
	''' These enums for Solr Order Types.
	''' </summary>
	''' <remarks></remarks>

Public Enum eSolrOrderTypes As Integer
	<Xml.Serialization.XmlEnum("0")>[ASC] = 0	
	<Xml.Serialization.XmlEnum("1")>[DESC] = 1	
End Enum


	''' <summary>
	''' TA-5380 / ARB-17: Algorithms for sorting child groups (e.g., sub-headings) underneath TOC headings.
	''' See also the TocHeading model class.
	''' </summary>
	''' <remarks></remarks>

Public Enum eTocGroupingSortingAlgorithm As Integer
	<Xml.Serialization.XmlEnum("0")>[unknown] = 0	
	<Xml.Serialization.XmlEnum("1")>[inherit] = 1	
	<Xml.Serialization.XmlEnum("2")>[alpha] = 2	
	<Xml.Serialization.XmlEnum("3")>[ordinal] = 3	
	<Xml.Serialization.XmlEnum("4")>[descendants] = 4	
	<Xml.Serialization.XmlEnum("5")>[derivedfromresources] = 5	
End Enum


	''' <summary>
	''' TA-5380 / ARB-17: Algorithms for sorting child artifacts (e.g., articles) underneath TOC headings.
	''' See also the TocHeading model class.
	''' </summary>
	''' <remarks></remarks>

Public Enum eTocArtifactSortingAlgorithm As Integer
	<Xml.Serialization.XmlEnum("0")>[unknown] = 0	
	<Xml.Serialization.XmlEnum("1")>[inherit] = 1	
	<Xml.Serialization.XmlEnum("2")>[alpha] = 2	
	<Xml.Serialization.XmlEnum("3")>[ordinal] = 3	
	<Xml.Serialization.XmlEnum("4")>[page] = 4	
	<Xml.Serialization.XmlEnum("5")>[date] = 5	
	<Xml.Serialization.XmlEnum("6")>[doi] = 6	
End Enum


Public Enum eAdvertistingTargetingTypes As Integer
	<Xml.Serialization.XmlEnum("1")>[Profession] = 1	
	<Xml.Serialization.XmlEnum("2")>[Specialty] = 2	
	<Xml.Serialization.XmlEnum("3")>[ClientFieldDefinition] = 3	
	<Xml.Serialization.XmlEnum("4")>[UserAffinity] = 4	
	<Xml.Serialization.XmlEnum("5")>[Category] = 5	
End Enum


	''' <summary>
	''' TA-5381: Drop smContentLoaderElements table and use config client settings instead for Zipline importing.
	''' </summary>
	''' <remarks></remarks>

Public Enum eZiplineConfigSettings As Integer
	<Xml.Serialization.XmlEnum("110")>[SftpDirectory] = 110	
	<Xml.Serialization.XmlEnum("111")>[BaseDirectory] = 111	
	<Xml.Serialization.XmlEnum("112")>[XslDirectory] = 112	
	<Xml.Serialization.XmlEnum("113")>[DtdDirectory] = 113	
	<Xml.Serialization.XmlEnum("114")>[ArchiveDirectory] = 114	
	<Xml.Serialization.XmlEnum("115")>[DeletePackage] = 115	
	<Xml.Serialization.XmlEnum("116")>[TagContent] = 116	
	<Xml.Serialization.XmlEnum("117")>[AlwaysExtractNewFolder] = 117	
End Enum




	''' <summary>
	''' TA-5696: Add substatus to upload config
	''' </summary>
	''' <remarks></remarks>

Public Enum eSmUploadSubStatuses As Integer
	<Xml.Serialization.XmlEnum("70")>[ArchivePackage] = 70	
	<Xml.Serialization.XmlEnum("50")>[CallSemedica] = 50	
	<Xml.Serialization.XmlEnum("90")>[Done] = 90	
	<Xml.Serialization.XmlEnum("20")>[LoadObjects] = 20	
	<Xml.Serialization.XmlEnum("60")>[MatchLinks] = 60	
	<Xml.Serialization.XmlEnum("80")>[SaveLog] = 80	
	<Xml.Serialization.XmlEnum("40")>[SaveObjects] = 40	
	<Xml.Serialization.XmlEnum("10")>[Unpack] = 10	
	<Xml.Serialization.XmlEnum("30")>[Validation] = 30	
End Enum


	''' <summary>
	''' TE-6969: Add Languages
	''' </summary>
	''' <remarks></remarks>

Public Enum eLanguages As Integer
	<Xml.Serialization.XmlEnum("0")>[Unspecified] = 0	
	<Xml.Serialization.XmlEnum("1")>[English] = 1	
	<Xml.Serialization.XmlEnum("2")>[Spanish] = 2	
	<Xml.Serialization.XmlEnum("3")>[Portuguese] = 3	
End Enum


	''' <summary>
	''' TE-7054, add GbosPubStateTypes
	''' </summary>
	''' <remarks></remarks>

Public Enum eGbosPubStateTypes As Integer
	<Xml.Serialization.XmlEnum("1")>[Created] = 1	
	<Xml.Serialization.XmlEnum("2")>[Edition] = 2	
	<Xml.Serialization.XmlEnum("3")>[Version] = 3	
	<Xml.Serialization.XmlEnum("4")>[Received] = 4	
	<Xml.Serialization.XmlEnum("5")>[Reviewed] = 5	
	<Xml.Serialization.XmlEnum("6")>[Revised] = 6	
	<Xml.Serialization.XmlEnum("7")>[Reaffirmed] = 7	
	<Xml.Serialization.XmlEnum("8")>[Updated] = 8	
End Enum



	''' <summary>
	''' These are eConfigBookSettings
	''' </summary>
	''' <remarks></remarks>
Public Enum eConfigBookSettings as Integer
	<Xml.Serialization.XmlEnum("145")>[SecondLevelHeadsNavigationOnContentPage] =145
End Enum


	''' <summary>
	''' Types of resource heirarchy structure available to the Outbound Content Package Generator
	''' </summary>
	''' <remarks></remarks>
Public Enum eOutboundContentPackageResourceStructureTypes As Integer
	<Xml.Serialization.XmlEnum("0")>[Normal] = 0	
	<Xml.Serialization.XmlEnum("1")>[GbosByPubDateDesc] = 1	
	<Xml.Serialization.XmlEnum("2")>[GbosByResourceIndexType] = 2	
	<Xml.Serialization.XmlEnum("3")>[GbosByCategory] = 3	
End Enum

	''' <summary>
	''' Import options
	''' </summary>
	''' <remarks>SCMP-704</remarks>
Public Enum eImportOption As Integer
    <Xml.Serialization.XmlEnum("0")> Undefined = 0 ' legacy magic value used in code only
        	<Xml.Serialization.XmlEnum("1")>[NewIssue] = 1	
        	<Xml.Serialization.XmlEnum("2")>[ReplacementArticle] = 2	
        	<Xml.Serialization.XmlEnum("3")>[ArticleBelongToExistingIssue] = 3	
        	<Xml.Serialization.XmlEnum("4")>[PublishAheadOfPrint] = 4	
        	<Xml.Serialization.XmlEnum("5")>[NewMultimedia] = 5	
        	<Xml.Serialization.XmlEnum("6")>[ReplacementMultimedia] = 6	
        	<Xml.Serialization.XmlEnum("7")>[ReplacementPAP] = 7	
        	<Xml.Serialization.XmlEnum("8")>[NewProceeding] = 8	
        	<Xml.Serialization.XmlEnum("9")>[ReplacementProceeding] = 9	
        	<Xml.Serialization.XmlEnum("10")>[JustAccepted] = 10	
        	<Xml.Serialization.XmlEnum("11")>[ReplacementJustAccepted] = 11	
        	<Xml.Serialization.XmlEnum("12")>[Retraction] = 12	
        	<Xml.Serialization.XmlEnum("13")>[ReplacementRetraction] = 13	
        	<Xml.Serialization.XmlEnum("14")>[ReplacementIssue] = 14	
        	<Xml.Serialization.XmlEnum("15")>[NewBook] = 15	
        	<Xml.Serialization.XmlEnum("16")>[NewGbos] = 16	
        	<Xml.Serialization.XmlEnum("17")>[ReplacementGbos] = 17	
        	<Xml.Serialization.XmlEnum("18")>[BookXmlFile] = 18	
        	<Xml.Serialization.XmlEnum("19")>[UpdateBookMeta] = 19	
        	<Xml.Serialization.XmlEnum("20")>[NewQuestionBank] = 20	
        	<Xml.Serialization.XmlEnum("21")>[GbosXmlFile] = 21	
        	<Xml.Serialization.XmlEnum("22")>[MultimediaXmlFile] = 22	
        	<Xml.Serialization.XmlEnum("23")>[SolQuizXmlFile] = 23	
        	<Xml.Serialization.XmlEnum("24")>[MixedIssues] = 24	
    End Enum

	''' <summary>
	''' Defines the timespan that a date field represents in a usage metrics table. Allows for use of dates to represent individual days, months, years, etc.
	''' </summary>
	''' <remarks></remarks>
Public Enum eUsageDateTypes As Integer
	<Xml.Serialization.XmlEnum("1")>[Month] = 1	
End Enum

	''' <summary>
	''' Defines multimedia supplement types
	''' </summary>
	''' <remarks></remarks>
Public Enum eMultimediaSupplementTypes As Integer
	<Xml.Serialization.XmlEnum("2")>[CME] = 2	
	<Xml.Serialization.XmlEnum("3")>[PodCast] = 3	
	<Xml.Serialization.XmlEnum("1")>[Transcript] = 1	
End Enum

	''' <summary>
	''' Defines SolLearnerTrackingQuizModes enumeration type
	''' </summary>
	''' <remarks></remarks>
Public Enum eSolLearnerTrackingQuizModes As Integer
	<Xml.Serialization.XmlEnum("2")>[Exam] = 2	
	<Xml.Serialization.XmlEnum("1")>[Review] = 1	
End Enum

	''' <summary>
	''' Defines SolLearnerTrackingQuizTypes enumeration type
	''' </summary>
	''' <remarks></remarks>
Public Enum eSolLearnerTrackingQuizTypes As Integer
	<Xml.Serialization.XmlEnum("2")>[FullQuiz] = 2	
	<Xml.Serialization.XmlEnum("3")>[FullQuizResumable] = 3	
	<Xml.Serialization.XmlEnum("1")>[OneByOne] = 1	
End Enum

	''' <summary>
    ''' userActivityStatus
    ''' </summary>
    ''' <remarks>Represents the userActivityStatus</remarks>
Public Enum eUserActivityStatus As Integer
	<Xml.Serialization.XmlEnum("1")>[Completed] = 1	
	<Xml.Serialization.XmlEnum("2")>[notApplicable] = 2	
	<Xml.Serialization.XmlEnum("3")>[Viewed] = 3	
End Enum

	''' <summary>
    ''' userActivityTypes
    ''' </summary>
    ''' <remarks>Represents the userActivityTypes</remarks>
Public Enum eUserActivityTypes As Integer
	<Xml.Serialization.XmlEnum("1")>[Bookmarks] = 1	
	<Xml.Serialization.XmlEnum("2")>[CaseHistory] = 2	
	<Xml.Serialization.XmlEnum("3")>[History] = 3	
End Enum


	''' <summary>
	''' These are the contentAssignmentRuleTypes
	''' </summary>
	''' <remarks></remarks>

Public Enum eContentAssignmentRuleTypes As Integer
	<Xml.Serialization.XmlEnum("1")>[Site] = 1	
	<Xml.Serialization.XmlEnum("2")>[Product] = 2	
End Enum


	''' <summary>
	''' These are the logEventTypes
	''' </summary>
	''' <remarks></remarks>

Public Enum eLogEventTypes As Integer
	<Xml.Serialization.XmlEnum("1")>[Debug] = 1	
	<Xml.Serialization.XmlEnum("2")>[Error] = 2	
	<Xml.Serialization.XmlEnum("3")>[Fatal] = 3	
	<Xml.Serialization.XmlEnum("4")>[Information] = 4	
	<Xml.Serialization.XmlEnum("5")>[Verbose] = 5	
	<Xml.Serialization.XmlEnum("6")>[Warning] = 6	
End Enum


	''' <summary>
	''' These are the TaskExecutionStatus
	''' </summary>
	''' <remarks></remarks>

Public Enum eTaskExecutionStatus As Integer
	<Xml.Serialization.XmlEnum("1")>[Started] = 1	
	<Xml.Serialization.XmlEnum("2")>[InProgress] = 2	
	<Xml.Serialization.XmlEnum("3")>[Completed] = 3	
End Enum


	''' <summary>
	''' These are the IssueTocTypes
	''' </summary>
	''' <remarks></remarks>

Public Enum eIssueTocType As Integer
	<Xml.Serialization.XmlEnum("1")>[Default] = 1	
	<Xml.Serialization.XmlEnum("2")>[CustomToc] = 2	
	<Xml.Serialization.XmlEnum("3")>[TopicDriven] = 3	
End Enum


	''' <summary>
	''' These are the SiteReleaseStages
	''' </summary>
	''' <remarks></remarks>

Public Enum eSiteReleaseStages As Integer
	<Xml.Serialization.XmlEnum("-1")>[Current] = -1	
	<Xml.Serialization.XmlEnum("1")>[Live] = 1	
	<Xml.Serialization.XmlEnum("2")>[Preview] = 2	
End Enum


	''' <summary>
	''' These are the DepositTypes
	''' </summary>
	''' <remarks></remarks>

Public Enum eDepositTypes As Integer
	<Xml.Serialization.XmlEnum("14")>[ADS] = 14	
	<Xml.Serialization.XmlEnum("21")>[ADSArticle] = 21	
	<Xml.Serialization.XmlEnum("20")>[AGI] = 20	
	<Xml.Serialization.XmlEnum("15")>[CDS] = 15	
	<Xml.Serialization.XmlEnum("22")>[CDSArticle] = 22	
	<Xml.Serialization.XmlEnum("9")>[CrossRef] = 9	
	<Xml.Serialization.XmlEnum("12")>[DataSalon] = 12	
	<Xml.Serialization.XmlEnum("8")>[DeepDyve] = 8	
	<Xml.Serialization.XmlEnum("16")>[KBART] = 16	
	<Xml.Serialization.XmlEnum("6")>[Muse] = 6	
	<Xml.Serialization.XmlEnum("5")>[Ovid] = 5	
	<Xml.Serialization.XmlEnum("17")>[OvidArticle] = 17	
	<Xml.Serialization.XmlEnum("2")>[PMCFull] = 2	
	<Xml.Serialization.XmlEnum("1")>[PMCNIH] = 1	
	<Xml.Serialization.XmlEnum("3")>[PMCSelective] = 3	
	<Xml.Serialization.XmlEnum("7")>[Portico] = 7	
	<Xml.Serialization.XmlEnum("11")>[PorticoArticle] = 11	
	<Xml.Serialization.XmlEnum("13")>[PTEPSCOAP3] = 13	
	<Xml.Serialization.XmlEnum("4")>[PubMed] = 4	
	<Xml.Serialization.XmlEnum("18")>[RSuite] = 18	
	<Xml.Serialization.XmlEnum("19")>[RSuiteArticle] = 19	
	<Xml.Serialization.XmlEnum("10")>[WebOfScience] = 10	
End Enum


	''' <summary>
	''' These are the IssueTypes
	''' </summary>
	''' <remarks></remarks>

Public Enum eIssueType As Integer
	<Xml.Serialization.XmlEnum("1")>[Regular] = 1	
	<Xml.Serialization.XmlEnum("2")>[Supplemental] = 2	
	<Xml.Serialization.XmlEnum("3")>[Continuous] = 3	
	<Xml.Serialization.XmlEnum("4")>[Theme] = 4	
End Enum


	''' <summary>
	''' These are the Restricted site states
	''' </summary>
	''' <remarks></remarks>

Public Enum eSiteState As Integer
	<Xml.Serialization.XmlEnum("3")>[hiddenlive] = 3	
	<Xml.Serialization.XmlEnum("0")>[previewonly] = 0	
	<Xml.Serialization.XmlEnum("2")>[publiclive] = 2	
	<Xml.Serialization.XmlEnum("1")>[restrictedlive] = 1	
End Enum


	''' <summary>
	''' These are the DepositStatuses
	''' </summary>
	''' <remarks></remarks>

Public Enum eDepositStatus As Integer
	<Xml.Serialization.XmlEnum("1")>[Scheduled] = 1	
	<Xml.Serialization.XmlEnum("2")>[Deposited] = 2	
	<Xml.Serialization.XmlEnum("3")>[DepositFailed] = 3	
	<Xml.Serialization.XmlEnum("4")>[ProcessedSuccessfully] = 4	
	<Xml.Serialization.XmlEnum("5")>[ProcessingFailed] = 5	
End Enum


	''' <summary>
	''' These are the SectionDTDs
	''' </summary>
	''' <remarks></remarks>

Public Enum eSectionDTDs As Integer
	<Xml.Serialization.XmlEnum("-1")>[Obsolete] = -1	
	<Xml.Serialization.XmlEnum("1")>[NLMJournal] = 1	
	<Xml.Serialization.XmlEnum("2")>[NLMBook] = 2	
	<Xml.Serialization.XmlEnum("3")>[ArtHW] = 3	
	<Xml.Serialization.XmlEnum("4")>[SCPsychoBook] = 4	
	<Xml.Serialization.XmlEnum("5")>[HW] = 5	
	<Xml.Serialization.XmlEnum("6")>[APPIJ] = 6	
	<Xml.Serialization.XmlEnum("7")>[HWQuiz] = 7	
	<Xml.Serialization.XmlEnum("8")>[AIPSgmlSPIN] = 8	
	<Xml.Serialization.XmlEnum("9")>[AIPSgmlFullText] = 9	
	<Xml.Serialization.XmlEnum("10")>[AIPXML] = 10	
	<Xml.Serialization.XmlEnum("11")>[BITS] = 11	
	<Xml.Serialization.XmlEnum("12")>[MGHBook] = 12	
	<Xml.Serialization.XmlEnum("13")>[HTML] = 13	
End Enum


	''' <summary>
	''' These are the ExternalLoginProviderHandlers
	''' </summary>
	''' <remarks></remarks>

Public Enum eExternalLoginProviderHandlers As Integer
	<Xml.Serialization.XmlEnum("1")>[ShibbolethExternalLoginProviderHandler] = 1	
End Enum


	''' <summary>
	''' These are the fieldTypes
	''' </summary>
	''' <remarks></remarks>

Public Enum eFieldTypes As Integer
	<Xml.Serialization.XmlEnum("1")>[TextBox] = 1	
	<Xml.Serialization.XmlEnum("2")>[DropDown] = 2	
	<Xml.Serialization.XmlEnum("3")>[TextArea] = 3	
	<Xml.Serialization.XmlEnum("4")>[ListBox] = 4	
	<Xml.Serialization.XmlEnum("5")>[CheckBox] = 5	
End Enum


	''' <summary>
	''' These are eSolrFacetFilterTypes
	''' </summary>
	''' <remarks></remarks>

Public Enum eSolrFacetFilterTypes As Integer
	<Xml.Serialization.XmlEnum("1")>[Default] = 1	
	<Xml.Serialization.XmlEnum("2")>[Expand] = 2	
End Enum

#End Region

end namespace


 
